### ISSUE TITLE
Sporadic localenv network error

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#1003]
Starting the localenv sometimes fails with:
```
network local_rafiki declared as external, but could not be found
 ELIFECYCLE  Command failed with exit code 1.
```

- https://github.com/interledger/rafiki/pull/779#discussion_r1030520448

**Comment by wilsonianb** [comment]
```
~/rafiki/infrastructure/local$ docker-compose logs
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.rafiki.ipam.config value Additional properties are not allowed ('gateway' was unexpected)
```

**Comment by mkurapov** [comment]
Was still a (on-and-off) issue for me when working on
- https://github.com/interledger/rafiki/pull/1148

@rluckom-coil maybe when working on the helm charts, you would be able to reproduce this and steer us in the right direction regarding this issue? seems like sort of a race condition where the `peer-docker-compose` tries to find the external `local_rafiki` network but it hasn't been created yet

**Comment by wilsonianb** [comment]
> ```
> ~/rafiki/infrastructure/local$ docker-compose logs
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> networks.rafiki.ipam.config value Additional properties are not allowed ('gateway' was unexpected)
> ```

Not sure if it will resolve this issue, but it sounds like we should remove `gateway`
https://docs.docker.com/compose/compose-file/compose-file-v3/#ipam
https://github.com/interledger/rafiki/blob/22360eb6c111819f9c1d2ac0c1a4919931d8030c/infrastructure/local/docker-compose.yml#L117
