### ISSUE TITLE
Create `GetReceiver` GraphQL Admin Query

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1005]
Now that we able to create "receivers" (remote or local incoming payments) via the `CreateReceiver` GraphQL admin mutation:
- #938 (issue)
- #986 (PR)

we should add a `GetReceiver` query to be able to fetch those details. We can leverage the `ReceiverService.get` method for this.

**Comment by sabineschaller** [comment]
This is for the account provider's information only, isn't it?
