### ISSUE TITLE
Update tigerbeetle testcontainer wait strategy

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#1009]
This message does not exist with version of TigerBeetle corresponding to the lastest version of `tigerbeetle-node`
https://github.com/interledger/rafiki/blob/dd07d2ff6f157c8b3fd671e9d74f7ea86e91ee5b/packages/backend/jest.setup.js#L98

https://github.com/tigerbeetledb/tigerbeetle/blob/main/src/tigerbeetle/main.zig

**Comment by sabineschaller** [comment]
So we need to update it together with updating `tigerbeetle-node`? Or is it already an issue in the version we are still using now?

**Comment by sabineschaller** [comment]
Blocked by #972
