### ISSUE TITLE
Open Payments Mandates API not mentioned in docs

### ISSUE THREAD

**Issue by networkimprov** [interledger/rafiki#106]
I'm drafting a proposal which entails calling the Open Payments Mandates API, much as a web browser would:
https://docs.openpayments.dev/mandates

I don't see mention of the Mandates API in the Rafiki docs. Is this in the plans? If so, is there a timeframe?

More context in https://github.com/WICG/webmonetization/issues/195

Thanks!

**Comment by AlexLakatos** [comment]
@sharafian is this something Rafiki currently supports, or is this going to be part of Stage 3?

**Comment by networkimprov** [comment]
It would really help to get clarification on this soon, as the deadline for GftW proposals is near.

cc @uchibeke @cairin

**Comment by AlexLakatos** [comment]
Mandates is part of Stage 3 of Rafiki, and the timeline revolves around this year. If you're looking at this as part of a GftW proposal, I'd say that's a good assumption to make in your proposal.

**Comment by networkimprov** [comment]
Awesome, thanks! I'll leave this issue open in case that API should be mentioned in Rafiki docs.

**Comment by AlexLakatos** [comment]
We've deprecated the Mandates concept in favour of Grants in Open Payments.
