### ISSUE TITLE
Decouple accountingService account creation from Tigerbeetle

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1088]
Currently, `accountingService.createSettlementAccount` method takes in a `ledger: number`, however, based on the psql accounting table structure (in #1087), we need to have account identifiers be _only_ strings

**Comment by sabineschaller** [comment]
> based on the psql accounting table structure (in https://github.com/interledger/rafiki/issues/1087), we need to have account identifiers be only strings

Why not just mimic tigerbeetles data structure and use a number here, too?

**Comment by mkurapov** [comment]
Closed with [comment](https://github.com/interledger/rafiki/pull/1079#issuecomment-1425015830)
