### ISSUE TITLE
Gracefully stop individual TB testcontainers

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1094]
When upgrading Tigerbeetle to the LSM tree version (plus node client to 0.11.11), github action backend tests would fail when stopping the individual tigerbeetle testcontainers for accounting and asset tests within the `afterAll`. A quick fix was to just remove that line and let the action itself stop all running containers once finished. 

We should find a way to reenable gracefully stopping these containers, potentially using jest [testEnvironment](https://jestjs.io/docs/configuration#testenvironment-string).

**Comment by sabineschaller** [comment]
Since we only use tigerbeetle in the accounting tests now, we can move back to globally starting and tearing down tigerbeetle (instead of doing it in the `beforeAll`/`afterAll` in the accounting tests).

**Comment by wilsonianb** [comment]
> Since we only use tigerbeetle in the accounting tests now, we can move back to globally starting and tearing down tigerbeetle (instead of doing it in the `beforeAll`/`afterAll` in the accounting tests).

I think the tigerbeetle testcontainer should still only start if the accounting tests run.
Not sure if it'd be possible to start it in the accounting tests but stop it in the jest global teardown

**Comment by mkurapov** [comment]
> Not sure if it'd be possible to start it in the accounting tests but stop it in the jest global teardown

I don't think this is possible unless we used a separate custom environment ([jest docs](https://jestjs.io/docs/25.x/configuration#testenvironment-string)) in order to share state. I have a old branch with this setup if necessary: https://github.com/interledger/rafiki/compare/972/mk/test-env
