### ISSUE TITLE
Fix tigerbeetle transfer timeouts

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1112]
In the connector middleware, we pass in 5 seconds into the `createTransfer` method, expecting the argument takes in nanoseconds:

https://github.com/interledger/rafiki/blob/40091b649120fdcd327706a424c5c672c4c3674a/packages/backend/src/connector/core/middleware/balance.ts#L56

However, the Tigerbeetle service method was actually expecting `ms`, since it converts the argument to `ns`:

https://github.com/interledger/rafiki/blob/40091b649120fdcd327706a424c5c672c4c3674a/packages/backend/src/accounting/tigerbeetle/transfers.ts#L88

We should standardize the `timeout` argument, maybe using `timeoutMs` for the method signature.

**Comment by wilsonianb** [comment]
related?
- https://github.com/interledger/rafiki/pull/228#discussion_r808463194

**Comment by AniqJaved** [comment]
I would like to work on this issue

**Comment by sabineschaller** [comment]
I just assigned you @AniqJaved

**Comment by AniqJaved** [comment]
Thanks for assigning this issue. But I wanted to ask that I will be able to change the name of parameter in the instances like these [rafiki/packages/backend/src/connector/core/middleware/balance.ts](https://github.com/interledger/rafiki/blob/40091b649120fdcd327706a424c5c672c4c3674a/packages/backend/src/connector/core/middleware/balance.ts#L56) but I wont to be able to change [these]([rafiki/packages/backend/src/accounting/tigerbeetle/transfers.ts](https://github.com/interledger/rafiki/blob/40091b649120fdcd327706a424c5c672c4c3674a/packages/backend/src/accounting/tigerbeetle/transfers.ts#L88)) as they are accessed through triggerbettle-node

**Comment by mkurapov** [comment]
@AniqJaved that's no problem, lets just have the consistent naming up until we pass it into the tigerbeetle API

**Comment by AniqJaved** [comment]
I have made a [PR](https://github.com/interledger/rafiki/pull/2123) , kindly let me know if I am at the right path.
