### ISSUE TITLE
Run Actions on MacOS 

### ISSUE THREAD

**Issue by sublimator** [interledger/rafiki#1140]
This will detect issues that turn up only on (the majority of) developer machines.

**Comment by sublimator** [comment]
e.g. https://github.com/tigerbeetledb/tigerbeetle/issues/451

**Comment by wilsonianb** [comment]
but the issues will soon only turn up on the minority of backend tests :stuck_out_tongue_winking_eye: 
- https://github.com/interledger/rafiki/pull/1139

**Comment by sublimator** [comment]
haha, regardless :)

**Comment by sabineschaller** [comment]
Since github only supports MacOS 12 and not the latest 13, it would not have caught the TigerBeetle issues. Also, testcontainers don't like MacOS. See
- #1288 

Hence, we decided not to add MacOS to the GH actions.
