### ISSUE TITLE
Support single phase transfers in connectors

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1166]
https://github.com/interledger/rafiki/issues/1016#issuecomment-1419081252

**Comment by sabineschaller** [comment]
@wilsonianb can you add some more details here? Why could we do a single phase transfer if `streamDestination === true`?

**Comment by wilsonianb** [comment]
:stuck_out_tongue_winking_eye: 
- https://github.com/interledger/rafiki/pull/730

**Comment by wilsonianb** [comment]
:point_up_2: that PR gave us this :point_down:
https://github.com/interledger/rafiki/blob/a27c1ea4a382182cb6191684d8ebe87c2426129f/packages/backend/src/connector/core/middleware/balance.ts#L77-L92
If this is the `streamDestination` then we've already called the subsequent middleware (`next`) and are needlessly doing a two phase transfer.
