### ISSUE TITLE
Mandate Creation API

### ISSUE THREAD

**Issue by sharafian** [interledger/rafiki#122]
- Mandates have an authorization token associated with them (we should make this as close to oauth as possible using the auth/refresh token pattern), which can be used to make API calls against the mandate
    - The parameters to create a mandate should allow metadata to be specified about the purpose of the mandate
- Mandates should have an API to make a payment to an SPSP endpoint
    - If the SPSP endpoint is an invoice, the amount to send can be pulled from the invoice's JSON response. If the SPSP endpoint is not an invoice, an amount must be provided with this API call.
    - Mandates have a limited amount of funds authorized (in this version we will allow then to be initialized with an amount of funds; in future versions this amount could be auto-refilling).
    - When this API is called, it should use the mandate's metadata and the invoice's metadata (if available) to create an entry in the user's transaction history in Rafiki

**Comment by wilsonianb** [comment]
>Mandates have a limited amount of funds authorized (in this version we will allow then to be initialized with an amount of funds; in future versions this amount could be auto-refilling).

I've gone ahead and implemented mandate intervals in https://github.com/wilsonianb/rafiki/tree/bw-mandates
However, I'm not sure how best to handle not refunding a mandate when a new interval starts within a [charge](https://docs.openpayments.dev/charges) payment's lifecycle.

A complicated scenario:

1. quote payment
2. deduct quoted amount from mandate (postgres, not tigerbeetle)
3. fund payment
4. sending fails
5. wallet calls `requoteOutgoingPayment` to retry
6. new quote needs additional funds
7. deduct additional amount from mandate
8. fund payment additional amount
9. sending fails
10. wallet calls `createOutgoingPaymentWithdrawal`

If all of this happens within the same mandate interval, `createOutgoingPaymentWithdrawal` should refund the full amount to the mandate.
If a new mandate interval starts after the second funding, nothing should be refunded to the mandate.
If a new mandate interval starts between the first and second fundings, the full amount should actually be deducted from the mandate in step 7. And `createOutgoingPaymentWithdrawal` should refund the full amount to the mandate.

Maybe the outgoing payment should store the mandate interval (`mandate.processAt`) to reference whenever it is funding or refunding a payment?

**Comment by wilsonianb** [comment]
Tracking mandate implementation (without api / authorization) in #211

**Comment by AlexLakatos** [comment]
We've dropped Mandates, can we close this down?
