### ISSUE TITLE
audit package.json(s)

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1307]
and only keep packages that are used

- [ ] backend
- [ ] auth
- [ ] token-introspection
- [ ] mock-account-servicing-entity
- [ ] local-http-signature
- [x] frontend

**Comment by mkurapov** [comment]
- [ ] backend
- [ ] auth
- [ ] token-introspection
- [ ] mock-account-servicing-entity
- [ ] local-http-signature
- [ ] frontend
