### ISSUE TITLE
knex isolation for concurrent backend tests

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#131]
While working on #129, I am encountering spurious backend test failures.
I think it is due to concurrent tests truncating postgres tables while they are still in use by other tests.
I've been unable to reproduce for the current `main`, but I think that can be explained by the current limited amount of table overlap among backend tests. My in progress changes are having more tests make use of the `accounts` table.

**Comment by matdehaast** [comment]
@wilsonianb this would be weird they conflict as jest serializes tests amongts workers. We specifically create a database per worker so this shouldn't be an issue
https://github.com/interledger/rafiki/blob/33823e179c238d6a245ab3d0769fd77194b8cd60/packages/backend/jest.setup.js#L51

**Comment by wilsonianb** [comment]
Ah, I'd forgotten about that.
In that case I'm not sure what was causing my test failures.
At this point it would be a task for me to revert my refactor work to investigate further.
How would you feel about us still switching over to testing with transactions instead of truncating tables a la https://github.com/wilsonianb/rafiki/commit/8772b48e56a51279a9940b8afcc856dc3b47f0c6 ?
(I'd open that as a pr after the send api is merged and before submitting a interledger/backend refactor pr.)

**Comment by wilsonianb** [comment]
I found my problem and am even more convinced to not test within a knex transaction:
https://github.com/wilsonianb/rafiki/blob/d98f8cd8542fb12181f135a909ece571180f7248/packages/backend/src/account/service.ts#L267-L280

Failing to `await` a transaction `commit()` caused no issues when testing within a transaction. (Maybe it's synchronous when it's a nested transaction / savepoint?)
Whereas testing directly, any test that created an account was a candidate to fail due to the new account(s) not being committed yet.
