### ISSUE TITLE
Interact with ASE on Payment Pointer request

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1419]
The Payment pointer GET request will publish a webhook to the ASE. Then, the ASE will do a payment pointer lookup on their own system, and be able to `createPaymentPointer`.

That means payment pointer information does not necessarily have to be stored within Rafiki anymore. On a GET request to the payment pointer, the request is forwarded to the ASE that populates the payment pointer details, and asyncronously creates the payment pointer (on the fly)

**Comment by mkurapov** [comment]
> ...synchronous hook to the ASE to request additional information.

Maybe "additional information" is not necessary to specify here since it's basically about replacing payment pointer storage altogether
