### ISSUE TITLE
Use tigerbeetle production release

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1438]
The first production release for TigerBeetle is `v0.15.3`. 
See https://npm.io/package/tigerbeetle-node

<img width="737" alt="image" src="https://github.com/interledger/rafiki/assets/1992108/b46eb509-e80b-4ceb-a493-9bb8be27cdb7">

<img width="740" alt="image" src="https://github.com/interledger/rafiki/assets/1992108/d89ecfb1-719a-491c-9c9c-bd0f9daa8821">

**Comment by koekiebox** [comment]
# PR for PROD release update:
https://github.com/interledger/rafiki/pull/2653

**Comment by sabineschaller** [comment]
Accomplished with #2653
