### ISSUE TITLE
Security mechanism for the Rafiki Admin API & UI

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1518]
## Summary
Currently, the GraphQL Admin API in Rafiki is using "same network" as a security concern. We'd like to explore and implement a more secure policy for it, looking at Basic Auth and MTLS.

The Admin UI is unsecured right now, we'll need to add login screens to that as well.

## Intended Outcomes
Design, spec and implement a security mechanism for the Admin API.

## How will it work?
There is a secure communication mechanism between the account provider and the backend service.

## Resources

- https://docs.confluent.io/platform/current/kafka/overview-authentication-methods.html#authentication-methods-overview
- https://www.cockroachlabs.com/docs/stable/authentication.html#client-authentication

## Todos
(not comprehensive)
- [x] #2200
- [x] #2218
- [x] #2491
- [x] #2492
- [x] #2493
- [x] #2494
- [x] #2495
- [ ] Testing?

**Comment by sabineschaller** [comment]
@JoblersTune do you want to research on how to best secure the admin UI?
