### ISSUE TITLE
Configure fees for an asset via Admin API

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1637]
## Context

For now, we can just introduce static, configurable fees for ASE to have simple fee structures managed by the backend admin API. 

```
type Mutation {
  updateFee(input: UpdateFeeInput!): UpdateFeeResponse!
}

input UpdateFeesInput {
  assetId: ID!
  type: 'SENDING' | 'RECEIVING'
  fee: {
    fixed: UInt64
    percentage: Float
  }
}

type Fee {
  id: ID!
  assetId: ID!
  type: 'SENDING' | 'RECEIVING'
  fixed: UInt64
  percentage: Float
}

type UpdateFeeResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  fee: Fee
}
```

The database changes would look like:

```
// fees table
{
  id  
  assetId
  type: 'SENDING' | 'RECEIVING'
  createdAt // will allow us to keep track of fees over time, most recent fees are grabbed by latest createdAt
  fixedFee
  percentageFee
}
```
Note that the fee structure is updated via adding a new column to the DB. Existing columns within the DB cannot be updated.

## Todo
- [ ] add new table to the postgres DB to store fee structure
- [ ] add mutation called `updateFees` to backend admin API to add or change fee structure
- [ ] update docs

**Comment by BlairCurrey** [comment]
Should both a fixed and flat fee value be required? or should you be able to just set one or the other? Or should you ONLY be able to set one or the other?

**Comment by mkurapov** [comment]
> Should both a fixed and flat fee value be required? or should you be able to just set one or the other? Or should you ONLY be able to set one or the other?

Reposting from Slack:

> not mutually exclusive, we would add both fixed and percentage fees on top of payments (during quoting), similar to how we do now in the /quotes route
If an ASE wants a fixed fee but not the percentage fee, they would set the percentage fee to be 0. Vice versa if they want a percentage fee and not a fixed fee

**Comment by mkurapov** [comment]
@sabineschaller  CC @BlairCurrey 
I think I had `activatedAt` as the timestamp to be used for looking up the most recently set fee. `createdAt` works of course, but I'm wary of using db-generated timestamps for business logic. While `activatedAt` will always be basically the same as `createdAt`, `createdAt` and `updatedAt` should be reserved only for database knowledge/debugging IMO. 
If our `BaseModel` changes to not auto-generated those timestamps, it isn't obvious it could break something

don't think 
I disagree with using t

**Comment by BlairCurrey** [comment]
> @sabineschaller CC @BlairCurrey I think I had `activatedAt` as the timestamp to be used for looking up the most recently set fee. `createdAt` works of course, but I'm wary of using db-generated timestamps for business logic. While `activatedAt` will always be basically the same as `createdAt`, `createdAt` and `updatedAt` should be reserved only for database knowledge/debugging IMO.
> 
> If our `BaseModel` changes to not auto-generated those timestamps, it isn't obvious it could break something

Seems fair. Perhaps not likely, but it's plausible we might want to mutate the field controlling the most recently set fee and we certainly shouldn't change the createdAt timestamp.
