### ISSUE TITLE
Update & move key registry documentation

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1667]
## Context

The current [key registry doc](https://rafiki.dev/concepts/open-payments/key-registry/) should live in the Open Payments site. Instead of this document, we should have a document explaining what it means for an ASE admin to add a key to a payment pointer.

**Comment by melissahenderson** [comment]
@mkurapov 
 
> we should have a document explaining what it means for an ASE admin to add a key to a payment pointer.

Does this address your request and, if so, is there anything else we need to do on the Rafiki side? https://rafiki.dev/integration/requirements/wallet-addresses/#create-a-wallet-address-key-pair

I have the content from the old Rafiki page and will check that the appropriate bits are in the Open Payments docs.

**Comment by mkurapov** [comment]
@melissahenderson this is good :+1: I think we can close this issue
