### ISSUE TITLE
Add liquidity to payments and payment pointers

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1694]
## Context

When querying payment pointers or incoming and outgoing payments using the Admin API, we want to also query the related payment liquidity and return it with the resource, just like we do it for assets and peers. This will allow us to display it on the admin UI and to allow liquidity deposit and withdrawal from the UI. Note that this does not apply to the Open Payments API, just the Admin API.

We should make sure to have the actual resolvers separately to the payment resolvers themselves, similar to how we do for assets and peers:
https://github.com/interledger/rafiki/blob/b39a05b83f3210856e195fd89c50574daa30d039/packages/backend/src/graphql/resolvers/index.ts#L53-L58

This will ensure that when someone _doesn't_ want this field, we don't make extra calls to the tigerbeetle db.

## Todos
add liquidity property to 
- [ ] incoming payment
- [ ] outgoing payment
- [ ] payment pointer

**Comment by njlie** [comment]
Does `liquidity` also need to be exposed on "Combined Payments" pages?

**Comment by njlie** [comment]
Closed in #2216
