### ISSUE TITLE
Make webhook event payload match OpenAPI spec

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1715]
## Context

The `outgoing_payment.completed` event is published with payload as `{ id, type, data: { payment: { ... }}}`, even though in the OpenAPI webhook spec, the event should be published as `{ id, type, data: { ... }}` (without the `payment` key).

We should match the code to return the data matching the OpenAPI spec. We should also confirm whether there are other webhook events that do the same incorrect behaviour.

## Todos
- [ ] Update webhook event payload to match OpenAPI webhook spec

**Comment by Cioraz** [comment]
Hey, I could resolve this. Could the issue be assigned to me?

**Comment by daniel-shuy** [comment]
Sorry @Cioraz, I already created a PR
