### ISSUE TITLE
Restrict account sending *or* receiving

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#175]
Replace the `disabled` account field with `sendEnabled` and `receiveEnabled`.
Outgoing payment accounts would have:
```
{
  sendEnabled: true,
  receiveEnabled: false
}
```
Invoice payment accounts would the opposite.
Peer account accounts would enable both.

Additional fields allowing depositing and/or withdrawing liquidity could also be added. (eg. disallow depositing to invoice account)

**Comment by sharafian** [comment]
I'm thinking this could be a good starting task for Damien. Also if we break disabled into sendEnabled and receiveEnabled, I think it would still be good to  have a flag that we can use to soft-delete accounts. Maybe just `finalized` as a field to indicate that an account is permanently disabled?

**Comment by wilsonianb** [comment]
I think the send/receive fields can just be enforced in [`transferFunds`](https://github.com/interledger/rafiki/blob/main/packages/backend/src/account/service.ts#L184), which I'm thinking should be relocated #177

**Comment by wilsonianb** [comment]
https://github.com/interledger/rafiki/pull/187 removed the accounts table.
The connector now only:
- sends from incoming peers (with incoming http token) and outgoing payments
- sends to outgoing peers (with ilp address) and invoices.
