### ISSUE TITLE
Fix debit vs credit

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#179]
Debit and credit accounts are swapped throughout Rafiki :upside_down_face: 
https://github.com/interledger/rafiki/blob/main/packages/backend/src/transfer/service.ts#L86-L87
Accounts/balances should default to `debitBalance`
https://github.com/interledger/rafiki/blob/main/packages/backend/src/balance/service.ts#L11

**Comment by sentientwaffle** [comment]
> Accounts/balances should default to debitBalance

In the interest of making the debit/credits more clear, I think there should be a `enum { CreditBalance, DebitBalance }`, and make it a required field when creating a balance (replacing the optional boolean).

**Comment by wilsonianb** [comment]
Joran says our current use of credit and debit accounts is ok.
#182 adds explicit `Credit` and `Debit` balance types to accounts and their balances.
