### ISSUE TITLE
outgoing http2 support

### ISSUE THREAD

**Issue by sentientwaffle** [interledger/rafiki#180]
- Right now outgoing payments are sent over HTTP/1, not HTTP/2.
- Also, we might want to support async http (or at least batching).

**Comment by sabineschaller** [comment]
We assumes this refers to to ILP packets being sent over http

**Comment by sabineschaller** [comment]
Axios does not support it, see [here](https://github.com/axios/axios/issues/1175).
Maybe this is only resolved when we do this
- #1036

**Comment by mkurapov** [comment]
Closing - any new code changes will use native fetch with http2 support
