### ISSUE TITLE
clean up accounts when empty incoming payment is deleted

### ISSUE THREAD

**Issue by sentientwaffle** [interledger/rafiki#181]
Per https://github.com/interledger/rafiki/issues/123, the `Invoice` is deleted when it expires without receiving any money. Right now it doesn't clean up the accounts (either the `Account` model or in TigerBeetle).

None of the following approaches prevent someone from just creating spam invoices continuously.

Ideas
- Lazily create the `Account` when a payment arrives.
  - Due to how ILP middlewares work, it would have to be created on Prepare, which doesn't entirely solve the issue.
  - The `paymentTag` needs to be the invoice id instead of the account id.
- Create the `Account` eagerly, but only create the TigerBeetle accounts when money arrives (i.e. on Fulfill).
- Delete the TigerBeetle accounts when the Invoice is deleted.
  - TigerBeetle doesn't support account deletion.

**Comment by wilsonianb** [comment]
~Invoices~ Incoming Payments no longer have an `Account` model for the TigerBeetle liquidity account (https://github.com/interledger/rafiki/pull/187). There is only the TigerBeetle account itself.

Does that mean the following could work?
>~Create the Account eagerly, but~ only create the TigerBeetle accounts when money arrives (i.e. on Fulfill).

**Comment by matdehaast** [comment]
@barnarddt is going to tackle this.
