### ISSUE TITLE
[Telemetry] - update Rafiki README with telemetry disclaimer

### ISSUE THREAD

**Issue by JoblersTune** [interledger/rafiki#1924]
Currently telemetry is enabled by default. This needs to be explicitly noted in the Rafiki README.

The README needs to explain exactly which metrics are being collected to inform users. It also needs to provide information about what is needed to enable telemetry or possibly where the metrics can be publicly viewed (these points still depend on exactly how the system is set up). As well as information on how to disable telemetry.

Depends on:
- #1956
- #1913

**Comment by mkurapov** [comment]
@beniaminmunteanu @JoblersTune is this something we can close with https://github.com/interledger/rafiki/pull/2299?

**Comment by beniaminmunteanu** [comment]
the fact that telemetry is enabled by default is not mentioned directly in the readme or in the docs. I can add that.
The metrics themselves are currently described in the docs, not sure if they should be added to rafiki readme, but maybe the rafiki readme can also link to the telemetry docs.
