### ISSUE TITLE
[BUG] No hyperlink for the rafiki pic in the documentation.

### ISSUE THREAD

**Issue by SOBANEJAZ** [interledger/rafiki#1973]
when we click on the rafiki pic in the documentation we are directed to a new tab with the picture on it.
We can make it a hyperlink that when someone clicks on the picture then he is directed to actual https://rafiki.dev/ website.

Please assign this issue to me for hactoberfest.

**Comment by Keshav-0907** [comment]
Can I work on this issue?

**Comment by SOBANEJAZ** [comment]
I have opened the issue and already requested to be assigned to me.
