### ISSUE TITLE
Point `fetch-schemas.sh` to latest OP spec.

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#1979]
The [fetch-schemas.sh script](https://github.com/interledger/rafiki/blob/main/scripts/fetch-schemas.sh) currently points to the [v1.0 tag](https://github.com/interledger/open-payments/releases/tag/v1.0) of Open Payments, which is outdated now.

Could be pointed to [5.0.0](https://github.com/interledger/open-payments/releases/tag/%40interledger%2Fopen-payments%405.0.0) but maybe this should wait until all the Open Payments changes get added and released. Then this could be pointed to that release instead.

**Comment by MarcelFox** [comment]
I want to give it a try @njlie can you assing this one to me?
