### ISSUE TITLE
Distinguish transfers from deposits and withdrawals

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#202]
Specify a `code` for Tigerbeetle transfers denoting the type.
Query account transfers by type to be able to determine things like what amount of an outgoing payments total debits are transfers as opposed to withdrawals.

**Comment by jorangreef** [comment]
@wilsonianb as soon as TB's LSM storage is running, we'll be able to provide the querying interface to query by `code`.

**Comment by sabineschaller** [comment]
TigerBeetle is now designing a Query API. Let's wait for that.
https://tigerbeetle.slack.com/archives/C0431SPEB61/p1679586883312349

**Comment by wilsonianb** [comment]
https://twitter.com/TigerBeetleDB/status/1638931604801302528

**Comment by mkurapov** [comment]
Closing until asked for

**Comment by melissahenderson** [comment]
@mkurapov Can we close this again? Linear re-opened it for some reason.
