### ISSUE TITLE
Open Payments Auth Redirect Website

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2032]
## Context

When a client requests a grant to create an outgoing payment, it needs to provide a url for the user to be redirected to after s/he has consented to the grant being issued on the consent screen. That redirect url is appended with query parameters, including the interaction ref, that the client needs to continue the grant request and get a token issued. 

When we go through the flow using postman, we don't have a page to redirect to. Currently we use example.com and just copy the interact ref out of the url in the url bar.

What we would like is a static page that parses the interact ref out of the url and displays it with a copy button. It should be included in `rafiki/localenv/redirect-page`.

Mockup (it can obviously be prettier than this)
<img width="862" alt="image" src="https://github.com/interledger/rafiki/assets/16089022/3d2f1da7-32d2-49d2-b793-7fe09b126399">

## Todos
- [ ] create a static page that parses the url and displays the interaction ref
- [ ] add copy button for interaction ref

**Comment by nooras** [comment]
Hi, 
Can you please assign me this task? I would like to give a try.
Thanks

**Comment by sabineschaller** [comment]
It's yours @nooras, have fun! 🙂

**Comment by Shubham2503** [comment]
Hey team, @sabineschaller @nooras 
Can I take this one if this issue is still open?

**Comment by nooras** [comment]
Hey @Shubham2503  i am working on this issue.
Thanks

**Comment by nooras** [comment]
HI @Shubham2503 I am not able to start local server so you can take it.
Thanks

**Comment by Shubham2503** [comment]
Yes @ashutuptiwari  I've started working on this

**Comment by ashutuptiwari** [comment]
Cool

**Comment by sabineschaller** [comment]
@Shubham2503 @ashutuptiwari , is this still being worked on?

**Comment by mkurapov** [comment]
Now with continuation polling this screen doesn't need the `interact_ref` finish url, but potentially we can convert this issue into "prettifying" the ASE interaction page.

**Comment by mkurapov** [comment]
Closing in favour of #2624
