### ISSUE TITLE
Identify unfulfillable rate probe packets

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#205]
https://github.com/interledger/rafiki/pull/197 stops balance adjustments from happening at the sending connector for unfulfillable rate probe packets.
Being able do them same for forwarding and receiving connectors would help avoid peer and asset liquidity from being reserved for unfulfillable packets.

**Comment by matdehaast** [comment]
@wilsonianb intermediate connectors could never know that the packets are unfulfillable as they can't decode the packet.

I am wondering if there could be an issue though with enabling this on the recievers side. I can't seem to think of anything in particular. @adrianhopebailie @sabineschaller do you think there are any potential footguns in not doing balance adjustments for probing packets?
