### ISSUE TITLE
Include handler for `payment_pointer.web_monetization` webhook event in Mock ASE

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2057]
## Context

The Mock ASE currently does not handle `payment_pointer.web_monetization` webhook events. Since it should also serve as a reference for actual integrators, all webhook events should be handled. 

**Note:** As of the creation of this issue, it is still called `payment_pointer`. However, we are in the process of changing this to `wallet_address`.

## Todos
- [x] include handler [here](https://github.com/interledger/rafiki/blob/main/localenv/mock-account-servicing-entity/app/lib/webhooks.server.ts)
- [x] handle event case [here](https://github.com/interledger/rafiki/blob/main/localenv/mock-account-servicing-entity/app/routes/webhooks.ts)

**Comment by sabineschaller** [comment]
Hi @manulpatel , it's yours 🙂

**Comment by Shubham2503** [comment]
Hey team, @sabineschaller @manulpatel, 
Can I take this one, if this issue is still open?

**Comment by BlairCurrey** [comment]
Currently the docs indicate calling the `WithdrawEventLiquidity` endpoint in this webhook handler. However, this handler is being deprecated and the new `WithdrawOutgoingPaymentLiquidity` resolver should be used instead.

Currently this webhook never fires. We might be able to manually test by doing:
- changing `walletAddressService.create` to do something like this: https://github.com/interledger/rafiki/commit/70a03ad05bb2798f42b2b24cde654848db348b6c
- create a new wallet address via postman
- call `triggerWalletAddressEvents` via postman which should trigger `handleWalletAddressWebMonetization`
