### ISSUE TITLE
Fix Rafiki Admin API Postman calls

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#2124]
The following API calls are failing in Postman:
* Open Payments APIs
	* Get Incoming Payment
	  * Returns "payment does not exist" even after running Create Incoming Payment, non-GraphQL version works in the Open Payments examples
	* ~~Deposit Event Liquidity~~
	  * ~~Returns "invalid id"~~
	* ~~Withdraw Event Liquidity~~
	  * ~~Returns "invalid id"~~
	* Create Wallet Address Withdrawal

Note: event liquidity are non-issue because id hardcoded in postman

* Open Payments Auth APIs:
  * Create Outgoing Payment
  * Token Rotation/Revocation

**Comment by sabineschaller** [comment]
@mkurapov and I went through all of them. They work now.
