### ISSUE TITLE
[Admin UI] Allow for Asset code of length 6

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2139]
## Context
The admin UI checks the length of the asset code and does not allow strings longer than 2. When talking to integrators, they mentioned that they need longer asset codes (e.g. for "USDT") and to be on the safe side, let's extend the max length to 6 on the admin UI.

## Todos
- [ ] extend allowed code length to 6 ([here](https://github.com/interledger/rafiki/blob/a77640e51d0dc2ee2d548b50bda0d85abea20b76/packages/frontend/app/lib/validate.server.ts#L90))

**Comment by Dhoni77** [comment]
Hi @sabineschaller  I would like to work on this.
