### ISSUE TITLE
Display OpenAPI specification on docs site

### ISSUE THREAD

**Issue by huijing** [interledger/rafiki#2192]
We want to display the OpenAPI specifications for webhooks and exchange rates in the sidebar just like how OpenPayments does it. See https://github.com/interledger/rafiki/tree/main/packages/backend/src/openapi for source files.

**Comment by sabineschaller** [comment]
related: https://github.com/interledger/rafiki/issues/1668

**Comment by mkurapov** [comment]
Closing in favour of #1668
