### ISSUE TITLE
Replace webhook service with liquidity service

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#221]
All [current](https://github.com/interledger/rafiki/blob/ff68afc9e86cb03436a4ad462efc0824438880c1/packages/backend/src/webhook/service.ts#L10-L19) (and [future](#220)) webhook events involve depositing or withdrawing payment liquidity.
`webhookService.send` could be replaced by `liquidityService.deposit`/`liquidityService.withdraw` so that callers do not need to manage the deposit/withdrawal.

However:

- Outgoing payments currently looks at the [webhook response code](https://github.com/interledger/rafiki/blob/main/docs/transaction-api.md#outgoing_paymentfunding) to cancel a funding payment or requote a cancelled payment. How could liquidity service methods expose/support that?
- Outgoing payments currently send `outgoing_payment.cancelled` and `outgoing_payment.completed` events even if there is not a leftover balance to withdraw. Are such events necesary? If so, could we keep a basic webhook service that the outgoing payments service calls directly in those cases?

**Comment by wilsonianb** [comment]
I started working on this as a part of #220 but got stuck on those open questions :point_up_2: 

https://github.com/wilsonianb/rafiki/tree/liquidity-service

**Comment by wilsonianb** [comment]
@sentientwaffle pointed out in the context of #223 that withdrawal transfer ids should be committed to postgres before creating the two-phase tigerbeetle transfers.
I'm thinking there should be withdrawal (and deposit?) tables managed by the aforementioned liquidity service, instead of tracking withdrawal details in the invoices, payments, and accounts (and eventually assets and peers) tables.

We could also add a webhook events table. Creating a withdrawal would create a webhook event, and the webhook service would manage the event lifecycle.

The liquidity service could have a worker querying pending withdrawals whose corresponding webhook events are in a resolved state.
The outgoing payment service could similarly query for payments in the Cancelled (or Funding) state whose corresponding withdrawal (or deposit) is resolved.
(Or something comparable if indexing can't make those join queries performant.)

>Outgoing payments currently looks at the webhook response code to cancel a funding payment or requote a cancelled payment. How could liquidity service methods expose/support that?

Storing the response status code on the webhook would allow an outgoing payment to see if the wallet instructed for the payment to be cancelled or requoted.

**Comment by sentientwaffle** [comment]
> withdrawal transfer ids should be committed to postgres before creating the two-phase tigerbeetle transfers.

More specifically, this is an issue if the transfer in question doesn't have a timeout. If it has a timeout, then it can get cleaned up automatically by TigerBeetle.

**Comment by wilsonianb** [comment]
I'm currently leaning towards the following:
- moving webhook persistence and retry logic to the webhook service (instead of duplicated across other services and tables)
- manage corresponding deposits and withdrawals in the webhook service
- set a webhook retry limit (to one day?) so that a single tigerbeetle transfer can be created per relevant webhook event
- no withdrawals table - tigerbeetle will be sufficient

My main TBD is how an outgoing payment updates state based on a response to a webhook retry.

**Comment by wilsonianb** [comment]
Closing in favor of #225
