### ISSUE TITLE
[BUG] Broken documentation links

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/rafiki#2242]
## Bug Report

**Describe the bug**

- All the relative links I've tried in `rafiki/package/documentation` are broken in both dev and production builds. 
- we are including the filetype in some places (see `./liquidity.md`) which doesnt work

We should just use absolute paths (no file extension) instead. 

Note that the relative links look correct if you're comparing against the source directory, but the built site adds an extra directory:

`docs/concepts/accounting/accounts-and-transfers.md` 

goes to 

`build/concepts/accounting/accounts-and-transfers/index.html`

**To Reproduce**

1.  Launch documentation dev server (`pnpm --filter documentation start`)
3. Navigate to Docs > Concepts > Accounting > Accounts and Transfers (http://localhost:1101/concepts/accounting/accounts-and-transfers/)
4. Click "SPSP" or "Web Monetization" link
5. See 404 and note the address is incorrectly nested under concepts (http://localhost:1101/concepts/reference/glossary#simple-payments-setup-protocol-spsp)
6. retry on production build and see the same (`pnpm --filter documentation build:docs && pnpm --filter documentation preview`)

**Expected behavior**

In the given example, the resulting link should be 
 http://localhost:1101/reference/glossary#simple-payments-setup-protocol-spsp
 
 Can achieve this by just using absolute links, like we do most places. For example:
 
 `/reference/glossary#simple-payments-setup-protocol-spsp`

instead of 

`../../reference/glossary#simple-payments-setup-protocol-spsp`

**Comment by ATREAY** [comment]
Hey @BlairCurrey, can I work on this issue if you are not already into it?

**Comment by BlairCurrey** [comment]
Go for it @ATREAY, thanks for the help

**Comment by ATREAY** [comment]
Hey @BlairCurrey, I have made the required changes, can please go through it whenever you have a moment?
