### ISSUE TITLE
Rename liquidity resolvers to use "deposit" instead of "add."

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/rafiki#2303]
## Context

We have some inconsistent liquidity resolver names as discussed here: https://github.com/interledger/rafiki/pull/2151#discussion_r1406673266

We use "add" in some places and "deposit" in others and decided to standardize on "deposit".

This will break integrator's where they call the existing endpoints and should be released with #1697.

## Todos
- [x] rename `addAssetLiquidity` -> `depositAssetLiquidity` and related names
- [x] rename `addPeerLiquidity` -> `depositPeerLiquidity` and related names
- [x] update frontend
- [x] update postman
- [x] update docs

**Comment by JoblersTune** [comment]
I found more instances of 'add'

- packages/backend/src/payment-method/ilp/auto-peering/errors.ts:` [AutoPeeringError.LiquidityError]: 'Could not add liquidity to peer'`
- packages/backend/src/payment-method/ilp/auto-peering/service.test.ts: `returns error if could not add liquidity during peer creation` and `returns error if could not add liquidity during peer update`
- packages/backend/src/payment-method/ilp/auto-peering/service.ts: `Could not add liquidity to peer`
- packages/backend/src/payment-method/ilp/peer/service.test.ts: `Add Liquidity` and `Can add liquidity to peer`
- packages/backend/src/payment-method/ilp/peer/service.ts: `error trying to add initial liquidity`
