### ISSUE TITLE
Test P2p flow

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/rafiki#2470]
Use the apollo client to implement the more basic Peer-to-Peer Payment flow from Bruno. Should prove to be the simpler flow to implement given some complications in the docker environment relating to the open payments client, running tests from host machine, and services in docker using proper domain names.

**Comment by mkurapov** [comment]
@BlairCurrey hmm, I wonder why this didn't get marked automatically completed - it should be, right?

**Comment by BlairCurrey** [comment]
I moved a few to Done on the kanban board and as I recall I had to manually close them. I presume I just missed this one.
