### ISSUE TITLE
Investigate way to improve docker environment (hostnames problem)

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/rafiki#2472]
Running tests from the hostmachine and services in docker presents some issues with URLs.

The tests need to make requests to localhost while the docker services need to use the real domain name (eg `http://cloud-nine-wallet-test-backend`). There are a few ways we could probably resolve this:

1. move the tests into docker. initially I didn't go this direction because I thought running from the host machine would make running and developing the tests easier but that may have presented more problems that it's worth
2. use nginx or similar and add domains to /etc/hosts. could perhaps get away without the `/etc/hosts` changes with this? https://kevinjalbert.com/access-local-docker-containers-by-domain-names-instead-of-ports/
3. Using host.docker.internal everywhere and map localhost to host.docker.internal in /etc/hosts
     - may be the most straightforward to implement but ultimately it would be best to use the actual domain names
     - example: https://github.com/interledger/rafiki/compare/main...mk/test-localenv-networking

**Comment by BlairCurrey** [comment]
I see 2 main options. Both include updating the integration tests and docker services to use the "real" urls like `http://cloud-nine-wallet-test-backend:3000`.

1. Put integration tests into docker
2. Add the hostnames to `/etc/hosts` and run locally.

And I think we can realistically do both. And should.

The main downside to running in docker is in local development where it requires more work to docekrize and has a harder to read output. But, it should just work which is a nice option, and I've already mostly set it up as can be seen in [this draft PR](https://github.com/interledger/rafiki/pull/2554). 

Running the tests from the host machine is a nicer experience but requires the one-time setup of editing the hosts file. Personally this is what I will opt for and think others will as well. It also doesn't require any additional proxy like I thought it might. Here is [a simple example detailing how this setup works](https://github.com/BlairCurrey/docker-hostname-experiment/tree/bc/add-etc-hosts-no-proxy) (basically, just add the entries in /etc/hosts).

For running in CI, both options seem good. The output isn't as important (and wont be pretty in any case) and mapping the hosts in /etc/hosts is simple.

**Comment by BlairCurrey** [comment]
Also, the current (or soon-to-be) status quo already requires editing `/etc/hosts` because the initial version uses `host.docker.internal` everywhere. https://github.com/interledger/rafiki/pull/2380

**Comment by mkurapov** [comment]
Even though it would have been nice for the proxy to work out of the box without changing the hosts file, like you said it is a pretty easy solution to change the file, particularly in a CI step, given we can just hardcode the host names.

Likewise, for the local playground, the only reason someone would need to edit the hosts file for is to be able to use the Open Payments client locally - and we can give instructions on how to do that.

**Comment by BlairCurrey** [comment]
> Even though it would have been nice for the proxy to work out of the box without changing the hosts file, like you said it is a pretty easy solution to change the file (maybe we can just do this automatically in the integration test script), particularly in a CI step, given we can just hardcode the host names.

Yeah I thought a proxy layer might resolve the need for mapping `/etc/hosts` but it's still required, and the proxy isnt necessary, so the proxy has no point. In generaly I wondered if there was something we can spin up in docker that will allow using real hostnames, but anything like that still needs to be accessed via localhost (as far as I can tell, and I guess that makes sense), so mapping in `/etc/hosts` seems like the only option. I suppose maybe some DNS service on the host machine might, but that's less simple than using `/etc/hosts`.

I considered handling the `/etc/hosts` in the integration script but I think the code to upsert is going to be more complicated than its worth, and I just generally don't love the idea of mutating everyone's system configuration (potentially without them knowing or understanding). I did see the VCS for [etckeeper](https://ubuntu.com/server/docs/tools-etckeeper) but don't think that works for us (don't really want force us to all use the same /etc/hosts). And it's just an additional dependency anyways - might as well just edit the hostfile.

**Comment by BlairCurrey** [comment]
After further discussion we've decided to set aside dockerizing it for now and run them from the hostmachine, using https://www.npmjs.com/package/sudo-prompt and https://www.npmjs.com/package/hostile in the `run-integration` script to automate host file edits. The required changes are simpler (just change the URLs and edit host files) and if we ever wanted to dockerize it, it would basically be a direct extension of this. Only potential edge case I can think of is that someone without root access will not be able to run the integration tests locally, but we may already require root access for development (docker, something else?) and tests can still be run against such changes in CI.

**Comment by BlairCurrey** [comment]
issue for the described changes: https://github.com/interledger/rafiki/issues/2555
