### ISSUE TITLE
Open Payments v2 `incoming-payment`

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#249]
Support Open Payments v2 [incoming-payment](https://hackmd.io/@openpayments2/ryVg6nQ15#2-Incoming-Payment) with existing [IncomingPaymentService](https://github.com/interledger/rafiki/blob/sb-incoming-payment/packages/backend/src/open_payments/payment/incoming/service.ts) and [API routes](https://github.com/interledger/rafiki/blob/sb-incoming-payment/packages/backend/src/open_payments/payment/incoming/routes.ts).
* rename properties
* add states
* ~Add STREAM receipt support~

**Comment by sabinebertram** [comment]
Depends on [this issue](https://github.com/interledgerjs/interledgerjs/issues/261)
