### ISSUE TITLE
Check outgoing payment grant

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#253]
- add token introspection query to configured AS (https://github.com/interledger/rafiki/pull/313)
- store grant id with payment
  - (lock and) check existing grant payments on payment creation

**Comment by wilsonianb** [comment]
>I think the grant needs to be evaluated for the creation and the auth. In the unlikely scenario that a payment is created at the end of an interval but then only authorised in the start of the next interval it should be accounted for in the second interval.
>
>As a basic rule, we should account for the outgoing payment at the moment it is authorised.
>
>But, checking the authorisation and balance available under the grant at creation does help to fail fast so we should do that too.

https://hackmd.io/YWnLmu9ASiiHIwTPzmZKNg

The outgoing payment's `sendAmount` is needed in order to check the grant's `sendAmount` limit. The earliest it can be checked is as follows:

|   | `FixedSend` | `FixedReceive` |
| --- | --- | --- |
| authorized on create | on create | on quote |
| authorized pre-quote | on authorize | on quote |
| authorized post-quote | on authorize | on authorize |

In order to check on quote, the grant's `sendAmount` limit (as seen when the payment was authorized) should be stored with the outgoing payment in Rafiki.

**Comment by wilsonianb** [comment]
In order to check an outgoing payment against its grant when the payment is quoted (see [above](https://github.com/interledger/rafiki/issues/253#issuecomment-1072506622) :point_up_2:), Rafiki needs the grant details in a context other than an Open Payments create or update request (when the grant is retrieved via access token introspection). Possible solutions include:

1. ~store the access token from the create/update request(s) and re-introspect~
2. allow Rafiki to query the grant by its id (`grant`) at the AS
3. store the grant with the outgoing payment
(This would duplicate a grant across multiple outgoing payments with the same grant)
4. store the grant on its own
(Should we overwrite the grant every time we see it, such that a request involving a different payment would cause us to compare the quoted outgoing payment with what is presumably the most recent version of the grant? Should grants have something like a revision number to determine what is actually the latest version?)

**Comment by jricher** [comment]
FWIW, I think option 4 is the cleanest -- you really are talking about managing a cached state of an external object. If there's a single "latest" state then a straight overwrite would work fine.

**Comment by sabineschaller** [comment]
I'm not sure I understand the use case. Isn't the payment quoted when it is created or updated? I thought the flow was
1. client -> RS: create|update
2. RS -> AS: introspect token
3. AS -> RS: token active, grant details
4. RS: get quote, check against grant
5. RS -> client: payment created|updated / creation|update denied
 OR
4. RS: kicks off quoting flow but doesn't wait for it
5. RS -> client: payment created|updated (but state could be Prepared after quoting, b/c grant is too little)

Or is it when the quote expired and we re-quote that we don't know about the grant?
