### ISSUE TITLE
Delete an unused asset

### ISSUE THREAD

**Issue by JoblersTune** [interledger/rafiki#2589]
## Context
The goal is to be able to delete an asset if no transactions were done for it, and no wallet/account is using it.
This will involve backend checks to ensure those requirements are met (any concerns about race conditions)
Then the GraphQL query will need to be created on the backend
And the Admin UI will also need to be updated accordingly
## Todos
- [ ]

**Comment by lengyel-arpad85** [comment]
@sabineschaller we could do a soft delete (have a time stamp for deletedAt), but then we have to make changes in more places to not display / use these, when creating a new one we would have to check if there is no asset with same code, but exclude deleted ones
also, from what I understood this is for the cases when someone creates an asset with a wrong code or scale (which aren't editable afterwards) ... what would be the benefit of keeping them ?

**Comment by lengyel-arpad85** [comment]
@sabineschaller well, my previous comment might be mute ... seems like tigerbeetle has no support for delete (at least I could not find any), so we have no way of deleting a record outside of psql, so only way is to mark them as inactive/deleted
