### ISSUE TITLE
Get account details

### ISSUE THREAD

**Issue by AlexLakatos** [interledger/rafiki#260]
The current get account details needs to be updated to the [new OPv2 spec ](https://docs.openpayments.guide/reference/get-public-account)

- [ ] Add the authServer as an env config value to Rafiki
- [ ] Add the ability to specify displayName when creating a paymentPointer on Rafiki
- [ ] Ensure the above properties are returned in the call to [getAccount](https://github.com/interledger/rafiki/blob/main/packages/backend/src/open_payments/account/routes.ts)

**Comment by matdehaast** [comment]
@omertoast is working on this.
