### ISSUE TITLE
[BUG] Webhook check for max retries causes processing of the same event

### ISSUE THREAD

**Issue by dragosp1011** [interledger/rafiki#2664]
Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.

## Bug Report
In recent release a new check for webhooks attempts was introduced that checks for max retries attempts ([PR](https://github.com/interledger/rafiki/pull/2541/files#diff-efa066cc9f163e17bcc35bfaa5a4bc80a60c56789c87f6b2e3dde96f5910013c)).
As the check is happening in the code that is causing the processing of the same events that reached the max attempts and does not go further to newly created webhooks. That is causing the system to be stuck and not processing new payments as the webhooks are not sent.
The events that reached max attempts should be ignored and not processed anymore.

**Comment by tadejgolobic** [comment]
GateHub had this problem today when we went into production. @mkurapov pointed out this issue, I bumped rafiki version to alpha.9 and everything started working. Thank you @dragosp1011 !
