### ISSUE TITLE
Return amount spent on the outgoing payment grant during outgoing payment creation

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2678]
## Context
For the web monetization extension (and very likely other use cases), we should know how much has already been spent on the outgoing payment grant. 

Whenever we create an outgoing payment, we determine whether the amount for the payment fits within the limits of the issued outgoing payment grant (by summing up all of the other payment that have been created under that said grant). If not, we reject the payment, otherwise, we create it. This accounting is done in the Open Payment resource server (the `backend` package), because that is where all of the outgoing payments are stored. In the auth server, we only know what the limit for the grant is, but not how much has been spent on it already.

This concerns the Open Payments outgoing payment, meaning there will be no changes in the Admin GraphQL API.

## Todos
- [x] https://github.com/interledger/open-payments/issues/469
- [ ] Return `grantSpentDebitAmount: Amount` and `grantSpentReceiveAmount: Amount` when creating outgoing payment

**Comment by BlairCurrey** [comment]
We talked about the reason for only returning on outgoing payment create, and that is because that is where the accounting is happening. We don't want to repeat that logic in a GET (especially for an entire page). We also concluded that returning in the create is sufficient for the webmon use-case.
