### ISSUE TITLE
Telemetry V2

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2695]
## Context

We want to extend the number of metrics we are collecting. 

* Number of prepare, fulfill, and reject packets
* Amount per fulfill packet
* Transaction time (per Open Payments outgoing payment)
* Transaction fees/conversions fee
* Transactions per wallet provider (not just rafiki instance): https://github.com/interledger/rafiki/discussions/2736
* Visualize node/peer graph: https://github.com/interledger/rafiki/discussions/2738

## Todos
- [x] #2734
- [x] #2735
- [x] #2737

**Comment by mkurapov** [comment]
I know there are outstanding discussions, but we can move that to Telemetry V3 IMO
