### ISSUE TITLE
Remove the `AccountingService` from middleware, and make use of the accounting service from backend

### ISSUE THREAD

**Issue by koekiebox** [interledger/rafiki#2712]
ILP connector middleware is currently making use of its own `AccountingService` interface. The interface should be replaced with the accounting interface from: `packages/backend/src/accounting/service.ts`

# See related:
https://github.com/interledger/rafiki/issues/2629

# PR:
https://github.com/interledger/rafiki/pull/2743

**Comment by sabineschaller** [comment]
Done with #2743
