### ISSUE TITLE
Admin UI payments page does not save type filter when navigating across pages

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2758]
## Context
Unlike the webhook events page, the payments page in the Admin UI does not persist the type when navigating across different pages:

https://github.com/interledger/rafiki/assets/15069181/61758a38-110f-4b7f-a92e-d6f10c2f2632

## Expected Behaviour
When selecting the type in the filter of the payments page, it should persist when navigating across pages of results.

**Comment by sarthakChauhan12** [comment]
Can I work on this issue?

**Comment by JoblersTune** [comment]
@sarthakChauhan12 I actually just added this fix while working on a related issue.
