### ISSUE TITLE
Create better docs for Admin UI and its auth

### ISSUE THREAD

**Issue by JoblersTune** [interledger/rafiki#2792]
## Context

Currently we have only got docs for the Admin UI and its auth functionality on rafiki.dev under the local playground tab.

We need to also create a separate tab for it in the docs and dig deeper into how it uses Kratos and what the setup is.

Currently we https://github.com/interledger/rafiki/tree/main/packages/frontend/README.md and touch on it under the local playground docs: https://github.com/interledger/rafiki/tree/main/localenv#admin-ui

Also useful to look at is information about our approach to user invitation: https://www.ory.sh/docs/kratos/manage-identities/invite-users

## Todos
- [ ] #2774

**Comment by brad-dow** [comment]
I have a Rafiki Admin UI User Guide draft in progress that will be added to the Rafiki docs as a new page. I'll link it here when it's ready for review.
