### ISSUE TITLE
[BUG] Admin UI displays liquidity in one asset scale and withdrawal input in a different scale

### ISSUE THREAD

**Issue by JoblersTune** [interledger/rafiki#2798]
## Bug Report

**Describe the bug**

When you view liquidity information it is displayed in asset scale two but when withdrawing liquidity it converts back to the original asset scale without warning the user.

**Expected behavior**

Either make it clear to the user that the asset scale has changed, or even better, make the asset scale consistent. 

**Screenshots**

![image](https://github.com/interledger/rafiki/assets/77615158/ff41c439-3534-4ce2-98ff-ba9d1a87b33a)
![image](https://github.com/interledger/rafiki/assets/77615158/f75ab702-da59-444c-94b4-aff5ece97b8b)
![image](https://github.com/interledger/rafiki/assets/77615158/fe62c28e-0805-4aff-b3db-7f639c05d796)

**Comment by JoblersTune** [comment]
@Emanuel-Palestino that would be lovely. Thanks for the offer of help!

> The expected result based on your screenshots is 9999999900.60 USD right? So the problem is that it is ambiguous on what scale the user is withdrawing or depositing, correct? 
Yes, exactly!

If you have any more questions please feel free to ask.

**Comment by JoblersTune** [comment]
For some additional context that might be helpful:
- I think this is a problem comes up for withdrawing or depositing liquidity for peers, assets, incoming and outgoing payments, and wallet addresses.
- The bug shows up whenever asset scale is not set to 0.
- The approach may be to use the loaders to get asset details and pass them into the liquidity dialog so that we can at least display 1 = $0.01 for instance.
- Also open to other suggestions if you have a different approach.

**Comment by Emanuel-Palestino** [comment]
I opened a pull request #2817 implementing your approach c:

**Comment by JoblersTune** [comment]
Fantastic @Emanuel-Palestino, thank you. I am out of office but will review on Wednesday when I am properly back at my desk.
