### ISSUE TITLE
tigerbeetle testcontainer crashes while running backend tests on macOS M1

### ISSUE THREAD

**Issue by omertoast** [interledger/rafiki#281]
I tried to run backend tests on two different Macbook Air M1 and when I used `yarn workspace backend test` I got the same error. The container in the context of the error is a Tigerbeetle container. Unlike the Tigerbeetle container, testcontainers container and Postgres container don't crash. I tried to check docker logs but the container crashes as it opens, so it wasn't possible to check logs at least for me. I don't have this problem on my Linux machine, that's why I believe the issue is related to macOS.

macOS version: Monterey 12.2.1
Node version: v14.19.0, v16.14.1, v17.6.0
Docker version: Docker Desktop for Mac 4.6.0
```
Error: Log stream ended and message "/listening on/" was not received for 42d7e88d9171a63a77e593d0a2e0c9478718d6aa2194c3656c8ed738c6a9f51b
    at LineStream.<anonymous> (/Users/omertoast/rafiki/.yarn/cache/testcontainers-npm-7.20.4-706f1bf23f-cb141138ae.zip/node_modules/testcontainers/dist/wait-strategy.js:112:28)
    at LineStream.emit (node:events:526:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by wilsonianb** [comment]
@jorangreef is this likely a Tigerbeetle + M1 issue?

**Comment by jorangreef** [comment]
@wilsonianb it could be an M1 issue that was fixed in December last year.

@omertoast would you please confirm the TigerBeetle git commit that you're running?

And would you please also provide the TigerBeetle log?

**Comment by omertoast** [comment]
@jorangreef I can't provide the TigerBeetle log because the container crashes instantly as soon as it opens. I tried several versions of the Tigerbeetle image, one of them being `sha256:0d8cd6b7a0a7f7ef678c6fc877f294071ead642698db2a438a6599a3ade8fb6f` as it's the one Rafiki main branch currently uses. I also tried @wilsonianb's fork but no luck on that one either.

I can run Tigerbeetle directly on mac but the containers crash when Rafiki tries to use `start` command, it doesn't have a problem with the `init` command tho. I think the problem is not the M1 issue that was fixed in December, instead, Docker seems like trying to emulate `amd64` to run Tigerbeetle (it also warns me about it) but fails to do it properly. I'll try to build Tigerbeetle for `arm64` and see if it's working.

**Comment by omertoast** [comment]
So I ran the Tigerbeetle container manually and have a chance to look at the log. I get the following error when trying to use the `start` command, unlike the `init` command which doesn't have this problem.
```
info(storage): opening "cluster_0000000001_replica_000.tigerbeetle"...
error: SystemOutdated
Unable to dump stack trace: MemoryMappingNotSupported
```
After searching the error, I found about [this closed issue](https://github.com/coilhq/tigerbeetle/issues/53). 

I get the following after running `uname -a` in the container

> Linux 3ab2f35748ef 5.10.104-linuxkit #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I also tried to use `strace` but I couldn't use it because of the following error

> /bin/sh: 1: strace: not found

**Comment by jorangreef** [comment]
Thanks for the information @omertoast it looks like you have a new enough Linux kernel for io_uring.

However, Docker apparently does not always expose io_uring syscalls automatically, so you may need to just try the solution here: https://github.com/coilhq/tigerbeetle/issues/53#issuecomment-946461241

**Comment by omertoast** [comment]
I forgot to mention that I already tried it and I got the same error.

**Comment by jorangreef** [comment]
Ah, okay.

In addition to that, you may also need to provide a Docker profile to tell Docker that it really should allow access to the io_uring syscalls, we have a sample Docker profile here: https://github.com/coilhq/tigerbeetle/blob/main/Dockerprofile.json

If that still doesn't work, then please try running TigerBeetle directly on your M1 machine and not through Docker so as to isolate the issue, by following these instructions: https://github.com/coilhq/tigerbeetle#quickstart

**Comment by omertoast** [comment]
Yup I can run TB directly on my Macbook Air M1 without an issue.

**Comment by sublimator** [comment]
This seems related to https://github.com/tigerbeetledb/tigerbeetle/issues/92#issuecomment-1277036191
