### ISSUE TITLE
LiquidityDialog UX improvements

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/rafiki#2825]
- Opening the `LiquidityDialog` should retain underlying page scroll position. Currently the asset page does not.
- Focus on the dialog input automatically

Original suggestion: https://github.com/interledger/rafiki/pull/2817#issuecomment-2250856417

**Comment by Emanuel-Palestino** [comment]
Hello, could someone assign this issue to me? I would like to work on it.

**Comment by mkurapov** [comment]
Closed with [feat(frontend): ux improvements to liquidity dialog component #2839](https://github.com/interledger/rafiki/pull/2839)
