### ISSUE TITLE
[BUG]: Admin UI got error when the session expires and the user tries to login again. It enters in an infinite auth loop.

### ISSUE THREAD

**Issue by Emanuel-Palestino** [interledger/rafiki#2840]
## Bug Report

**Describe the bug**

When the session at the Admin UI expires, appears the welcome page to login again. If the user tries to login again using the welcome page that appears in the interface, it gets a 404 error.
Then if the user click the `Go to homepage` button, it's redirected to root `auth` page, so if the user tries to login, it gets the 404 error over again.

**To Reproduce**

> Important: Don't reload the page at any time.

1. Run the rafiki instance
2. Go to Admin UI and login
2. Using the developer tools of your browser, delete the page cookies. (This is made in order to simulate the session expiration).
3. Now, try to move to another section (wallets, peers, wallet details, etc).
4. Try to login again, using always the buttons that appears in the interface.
5. You will enter in the auth loop.

**Screenshots**

1. Session expired, welcome page appears.
![image](https://github.com/user-attachments/assets/6601335a-cdd1-4ff0-8d8f-13337c6abb7e)
2. You try to login again, you got the 404 error.
![image](https://github.com/user-attachments/assets/d0626829-b179-4b2f-9676-41a98164cf72)
3. If you try to go to homepage and login, you got the same error.
![image](https://github.com/user-attachments/assets/787d07c4-0842-4a44-8fc7-741ab41acd13)

I think this is not a correct behavior. The user should be able to login again without the need of reload the page.

**Comment by golobitch** [comment]
What version of rafiki-frontend are you running?

**Comment by Emanuel-Palestino** [comment]
I am running the v1.0.0-alpha.15 of rafiki c:

**Comment by DarianM** [comment]
Let's use `redirectDocument` instead of `href` when redirecting to `auth` page
