### ISSUE TITLE
[Multi-tenant Rafiki] Update all resources to have a tenantId foreign key

### ISSUE THREAD

**Issue by sanducb** [interledger/rafiki#2894]
## Context

Any Rafiki tenant must be able to only access it's own resources, therefore `tenantId`foreign key should be added for quotes, incoming and outgoing payments resources, wallet addresses.

## Todos
- [x] Add `tenantId` foreign key for each of the resources mentioned above

**Comment by njlie** [comment]
Added in #2969.
