### ISSUE TITLE
Add deactivating wallet address functionality to Rafiki Admin

### ISSUE THREAD

**Issue by JoblersTune** [interledger/rafiki#2902]
Currently you can create wallet addresses on Rafiki Admin but not deactivate them. We want to add in this functionality since it does exist on the backend.

**Comment by JoblersTune** [comment]
Fantastic. I think @melissahenderson was asking. I'll close the issue. Thanks Max.

**Comment by melissahenderson** [comment]
@brad-dow Tagging you for awareness
