### ISSUE TITLE
Docs: update Overview (for Integrations > Deploy to Prod)

### ISSUE THREAD

**Issue by tselit** [interledger/rafiki#2931]
## Context
Expand content in this section: Integration > Deployment > Deploy to production

## Todos
- [ ] setup meetings with Max & Roberto to understand all elements of Security for deploying to Prod (SSL; mTLS; Secrets; Certificates)
- [ ] update the Ooverview section based on the above discussions

**Comment by hajjimo** [comment]
Based on discussion between tech writers and Max on 09/23, some security practices (e.g. use of certificates) can be called out in line in the deployment guides and/or integrator checklist.  Other practices are commonplace (e.g., using https), so they don't necessarily have to be called out explicitly.
