### ISSUE TITLE
Docs: Clarify separate auth server endpoints for IDP implementation

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/rafiki#2946]
In a meeting with an integrator about implementing IDP, it was suggested to have better documentation about the separate auth server endpoints. They noted that the separate interaction server endpoint was unexpected and they had to dig into the code to realize it existed.

Perhaps include distinction between different endpoints here? https://rafiki.dev/concepts/open-payments/grant-interaction/

These routes were factored out fairly recently in https://github.com/interledger/rafiki/pull/2665

**Comment by melissahenderson** [comment]
If needed as a reference: http://web.archive.org/web/20240225105323/https://rafiki.dev/concepts/open-payments/grant-interaction/

**Comment by melissahenderson** [comment]
Resolved by #2977
