### ISSUE TITLE
Docs: Fix markdown tables

### ISSUE THREAD

**Issue by melissahenderson** [interledger/rafiki#2951]
Most (not all) of the markdown tables look pretty bad. This is especially the case where the first column contains long variable names. 

We need to convert these tables into HTML tables. But first, we need to figure out how we want to style the tables so they're consistent across pages.

**Comment by brad-dow** [comment]
**TEXT FORMATTED AS CODE LINE BREAKS**
I think we can remedy these tables in a way where we don't have to use raw HTML. After doing a little bit of digging on the project, I can see that the main ILF-docs.css file in the core docs-design-system has a line that defines way lines break specifically when the text is formatted as code in a table:

> table code {
  word-break: break-all;
}

There are a few ways to handle this:

- We can modify the docs-design-system CSS to not break up text formatted as code in a table.
- If this is only a Rafiki problem (which I don't think it is), we can alter the rafiki.css to override that style

If we want to pursue the first option, we'll need to update the docs-design-system CSS and then update all of the other docs pages' dependencies in package.json

If we want to handle it within rafiki.css, it's as simple as making updates as seen in this branch: https://github.com/interledger/rafiki/tree/docs-table-updates

**Comment by brad-dow** [comment]
**TABLES THAT EXTEND PAST THE MAIN CONTENT AREA**
In playing around with some markdown tables, I noticed that a table will extend into the right sidebar navigation area. By wrapping the markdown table in a custom div class, we can alter this behavior with a few CSS tweaks. 

To see this functionality, run this branch locally: https://github.com/interledger/rafiki/tree/docs-table-updates

**Comment by brad-dow** [comment]
I've created a PR of my work thus far for @JoblersTune to review and enhance when she gets the chance.

https://github.com/interledger/rafiki/pull/2990
