### ISSUE TITLE
Technical review of OpenAPI specs

### ISSUE THREAD

**Issue by brad-dow** [interledger/rafiki#2958]
Rafiki has four OpenAPI specs in the code base. After reviewing the webhooks spec and [noticing some incomplete areas](https://github.com/interledger/rafiki/issues/2920), it would be a good idea to review all four:

- [Webhooks](https://github.com/interledger/rafiki/blob/main/packages/backend/src/openapi/specs/webhooks.yaml)
- [Exchange Rates](https://github.com/interledger/rafiki/blob/main/packages/backend/src/openapi/specs/exchange-rates.yaml)
- [Identity Provider](https://github.com/interledger/rafiki/blob/main/packages/auth/src/openapi/specs/id-provider.yaml)
- [Token Introspection](https://github.com/interledger/rafiki/blob/main/packages/token-introspection/src/openapi/specs/token-introspection.yaml)

**Comment by mkurapov** [comment]
@oana-lolea other than the IDP spec, were all the other specs valid/not missing anything?
