### ISSUE TITLE
Allow `accountId` to be a string, not just uuid

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#296]
Currently, `accountId`s in incoming and outgoing payments are uuids. For user-friendliness, we would also want to allow for human-readable id's, such that a payment pointer can be e.g. https://openpayments.guide/alice and not only https://openpayments.guide/016da9d5-c9a4-4c80-a354-86b915a04ff8.

**Comment by DonChangfoot** [comment]
@wilsonianb mentioned maintaining a blocklist so that canonincal urls like `/graphql` are not confused with account names (#322 ).

**Comment by wilsonianb** [comment]
> @wilsonianb mentioned maintaining a blocklist so that canonincal urls like `/graphql` are not confused with account names (#322 ).

- That should be less of an issue once https://github.com/interledger/rafiki/issues/441 is resolved

**Comment by wilsonianb** [comment]
- Duplicate of https://github.com/interledger/rafiki/issues/416
