### ISSUE TITLE
Update (required) environment variables in docs

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2975]
## Context
In the rafiki docs, we should specify which environment variables are required and which ones are not.

#### Backend
OPEN_PAYMENTS_URL
ILP_ADDRESS
ILP_CONNECTOR_URL
INSTANCE_NAME
AUTH_SERVER_GRANT_URL
AUTH_SERVER_INTROSPECTION_URL
WEBHOOK_URL
KEY_ID 
EXCHANGE_RATES_URL
USE_TIGERBEETLE
DATABASE_URL
REDIS_URL

#### Auth
IDENTITY_SERVER_URL
IDENTITY_SERVER_SECRET
AUTH_SERVER_URL
COOKIE_KEY
AUTH_DATABASE_URL
REDIS_URL

#### Frontend
GRAPHQL_URL
OPEN_PAYMENTS_URL

**Comment by mkurapov** [comment]
@melissahenderson I would recommend potentially we have these presented first and separate from the other environment variables (ie not have them in a single table). Might be clearer trying to find all of the required things off the bat.

**Comment by melissahenderson** [comment]
This is currently in progress, but not yet in GH. I have all the env variables I can find split into google docs for auth, backend, and frontend and they are being reviewed--accuracy in naming, helm value, default value, description... So this issue will be taken care of when those reviews are complete and the environment tables in Starlight are all updated as needed.

**Comment by melissahenderson** [comment]
#2994 is related and there will likely be other issues opened for auth and backend.

**Comment by melissahenderson** [comment]
Auth doc is good, no further questions or issues. Frontend still reliant on #2994. Backend still has a lot of outstanding Helm issues and is missing variable descriptions.

**Comment by brad-dow** [comment]
New backend environment variable and associated issue: https://github.com/interledger/rafiki/issues/3035

**Comment by melissahenderson** [comment]
Added to Google Doc so it won't be overwritten in the Rafiki docs when I get to those updates.

**Comment by melissahenderson** [comment]
PR #3042 cares for this issue; however, the PR can't be merged until #2994 is complete.
