### ISSUE TITLE
Cache wallet addresses

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2982]
### Context

During Rafiki WW, one of the performance optimizations we found to be useful is caching assets, given we make so many requests for wallet addresses, even though they rarely change. 

We should use redis for caching these.

### Todo
- [x] Add redis cache to walletAddressService (via `createRedisDataStore`, and a reasonable key expiry). Delete cache on wallet address `update`.
- [x] Resolve any requests for assets via the assetService instead of any `.withGraphFetched('walletAddress')` objection calls

**Comment by koekiebox** [comment]
Note, the Redis cache was replaced in favour of the temporary local cache. The local cache stores the data for 5 seconds.
