### ISSUE TITLE
Docs: Remove pages that aren't in the left nav menu

### ISSUE THREAD

**Issue by brad-dow** [interledger/rafiki#2997]
I identified three pages that aren't linked in the left nav menu, but show up in the site search:

- https://rafiki.dev/overview/concepts/accounts-transfers-liquidity
- https://rafiki.dev/admin/manage-keys/
- https://rafiki.dev/admin/manage-grants/

I'm pretty sure the keys and grants pages are placeholders, but I know we've replaced accounts-transfers-liquidity with the accounting page. We need to remove these pages or at least hide them from search indexing if possible.

**Comment by melissahenderson** [comment]
There's also integration > peering.

**Comment by brad-dow** [comment]
https://github.com/interledger/rafiki/pull/3006
