### ISSUE TITLE
Configure payment sending attempts

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#3017]
## Context
Currently, in backend, we are unable to configure the amount of times a payment is retried. Instead, we have a magic number:
https://github.com/interledger/rafiki/blob/af2ca8e2c4d3542c4be04d68f0e2c8a1cdf425d2/packages/backend/src/open_payments/payment/outgoing/worker.ts#L13

This should be a configurable ENV variable.

## Todos
- [ ] Allow payment sending to be a configurable property
- [ ] Make a `user-docs` issue to have the writers add this new env variable to the docs

**Comment by dead8309** [comment]
Hey can i do this one ? from my understanding of codebase 
- we have to add a new env config field
- add `IAppConfig` field in
https://github.com/interledger/rafiki/blob/af2ca8e2c4d3542c4be04d68f0e2c8a1cdf425d2/packages/backend/src/open_payments/payment/outgoing/service.ts#L61
- and access it in 
https://github.com/interledger/rafiki/blob/af2ca8e2c4d3542c4be04d68f0e2c8a1cdf425d2/packages/backend/src/open_payments/payment/outgoing/worker.ts#L97

Happy to open a pr if this is the correct way

**Comment by sabineschaller** [comment]
Hi @dead8309, yes, that should be it. I'll assign you. Thank you and looking forward to this PR 🙂!
