### ISSUE TITLE
Update Rafiki style guide with custom table styles

### ISSUE THREAD

**Issue by brad-dow** [interledger/rafiki#3036]
Update https://interledger.net/content/rafiki/ with something similar to the following:

`overflow-table` -> **this should work for most larger tables**
A long and wide table (vertical and horizontal scrollbars on overflow) with regular columns

`overflow-table wide-column`
A long and wide table (vertical and horizontal scrollbars on overflow) that needs extra wide columns to accommodate text formatted as code (variable names, etc.)

`overflow-table wider-column`
A long and wide table (vertical and horizontal scrollbars on overflow) that needs even larger, extra wide columns to accommodate text formatted as code (variable names, etc.)

I'm a bit unsure of the differences between wide-column and wider-column, but we can figure those out as we go.

**Comment by huijing** [comment]
@brad-dow `wide-column` sets the minimum width of the table (sum total width of all columns) to 60rem, while `wider-column` sets the minimum width of the table to 80rem.
What this means is that columns with normal content have more room to stretch out with `wider-column`
