### ISSUE TITLE
Tests don't run on 2018 macbook pro intel

### ISSUE THREAD

**Issue by tyleralt** [interledger/rafiki#341]
Currently running the backend tests is broken on my computer. I have a 2018 macbook pro.

When I run ```yarn workspace backend test``` I get the following output 
<img width="836" alt="image" src="https://user-images.githubusercontent.com/9980096/168695129-ff3ba617-3f88-4eb7-8584-2f2a7d696552.png">

 I traced the issue to the tigerbeetle docker images attempting to be run in on this [line](https://github.com/interledger/rafiki/blob/557fe12851bb7d34911dcba13d8724cee0403f83/packages/backend/jest.setup.js#L71). 

If you attempt to start the image by itself you get 
<img width="834" alt="image" src="https://user-images.githubusercontent.com/9980096/168695300-42eddc09-e73f-4f95-bf84-ba13b24c1f60.png">

There is an [issue](https://github.com/coilhq/tigerbeetle/issues/92) in the tigerbeetle repo referencing this same problem.

**Comment by tyleralt** [comment]
I was thinking of putting a small addendum to the prerequisite in the backend [readme](https://github.com/interledger/rafiki/blob/557fe12851bb7d34911dcba13d8724cee0403f83/packages/backend/README.md?plain=1#L5) with an easy work around if that sounds reasonable.

**Comment by sublimator** [comment]
@tyleralt 

Did the tests all work for you once you applied the workaround ?
