### ISSUE TITLE
Make consent screen location configurable

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#378]
In the current flow, the consent screen is hosted by the Wallet provider / Identity server (IS). We want to make the location of that configurable such that both, the IS and the GNAP AS, can host it.

**Comment by njlie** [comment]
https://github.com/interledger/rafiki/pull/370 added a configurable variable [in the configuration](https://github.com/interledger/rafiki/blob/main/packages/auth/src/config/app.ts#L30) that allows the AS to configure the consent screen location. Closing.
