### ISSUE TITLE
Add Account Service spec to docs folder

### ISSUE THREAD

**Issue by sharafian** [interledger/rafiki#39]
currently this lives in notion; it would be nice to have it publicly available

**Comment by vladimirfomene** [comment]
@sharafian and @kincaidoneil, I'm new to the community and I will like to contribute. Can I help out with this task or any other task?

**Comment by matdehaast** [comment]
@vladimirfomene welcome! 

Are you looking to do technical or non technical work?

**Comment by vladimirfomene** [comment]
Hello @matdehaast, I'm inclined towards technical work but non technical work will also do. Thanks!
