### ISSUE TITLE
Privilege minimization for Tigerbeetle, rafiki-backend docker containers

### ISSUE THREAD

**Issue by rluckom-coil** [interledger/rafiki#400]
In our discussions around the issue to make a [helm chart for rafiki](https://github.com/interledger/rafiki/issues/232), we decided to initially use `privileged` mode for the Tigerbeetle container and the rafiki-backend container which uses the tigerbeetle client. During the Rafiki Summit we want to try to minimize the required permissions rather than using privileged mode.

**Comment by sabineschaller** [comment]
We use the recommended `--cap-add IPC_LOCK` now.
