### ISSUE TITLE
Document Rafiki Concepts

### ISSUE THREAD

**Issue by AlexLakatos** [interledger/rafiki#491]
Feel free to create individual issues for answering these questions if that's easier for you.
- [x] What is Rafiki?
- [x] Who is the intended audience for Rafiki?
- [x] What are the overall architecture and design decisions?
- [x] What is the Admin API?
- [x] What are the Open Payment APIs?
- [x] What is an Account Provider?
- [x] What are the integration points for an Account Provider?
  - [x] What is GNAP?
  - [x] What is the AS?
  - [x] How do Rates & Fees work?

**Comment by sabineschaller** [comment]
> What is Rafiki?
> Who is the intended audience for Rafiki?

Readme.md

> What are the overall architecture and design decisions?

docs/architecture.md

> What is the Admin API?

docs/admin-api.md

> What are the Open Payment APIs?

docs/open-payments.md

> What is an Account Provider?
> What is GNAP?

docs/glossary.md

> What are the integration points for an Account Provider?
> What is the AS?
> How do Rates & Fees work?

docs/integration.md
