### ISSUE TITLE
Document the TigerBeetle usage in Rafiki

### ISSUE THREAD

**Issue by AlexLakatos** [interledger/rafiki#498]
- [x] What is TigerBeetle (from a non-developer perspective)?
- [ ] Why are we using TB?
- [ ] How are we using TB in Rafiki?
  - [x] Document the Chart of Accounts
  - [ ] Document the flows that use TB
  - [ ] How do we upgrade TB in Rafiki?
  - [ ] Running a TB cluster & requirements
    - [ ] Describe the consensus, limitations, and strategies for designing your TB cluster.

**Comment by wilsonianb** [comment]
>What is TigerBeetle (from a non-developer perspective)?

https://github.com/coilhq/tigerbeetle
_TigerBeetle is a financial accounting database designed for mission critical safety and performance to power the future of financial services._

>Document the Chart of Accounts

https://github.com/interledger/rafiki/tree/main/packages/backend#design

>How do we upgrade TB in Rafiki?

`pnpm --filter backend add -P tigerbeetle-node`
https://github.com/interledger/rafiki/blob/main/packages/backend/package.json#L89
https://www.npmjs.com/package/tigerbeetle-node

**Comment by sabineschaller** [comment]
@wilsonianb 
> https://github.com/interledger/rafiki/tree/main/packages/backend#design

I think this needs a bit more explanation.

> `pnpm --filter backend add -P tigerbeetle-node`

That's not all of it, at least right now.

**Comment by wilsonianb** [comment]
> * [x]  What is TigerBeetle (from a non-developer perspective)?

https://github.com/interledger/rafiki/blob/main/docs/glossary.md#tigerbeetle

>     * [ ]  Why are we using TB?

TODO?

>     * [ ]  How are we using TB in Rafiki?
>       
>       * [x]  Document the Chart of Accounts
>       * [ ]  Document the flows that use TB

- https://github.com/interledger/rafiki/pull/1191
>       * [ ]  How do we upgrade TB in Rafiki?

I don't currently know the answer to this question :sweat_smile: 
- https://github.com/interledger/rafiki/pull/1181

>       * [ ]  Running a TB cluster & requirements
>         
>         * [ ]  Describe the consensus, limitations, and strategies for designing your TB cluster.

I vote we defer to https://docs.tigerbeetle.com/

**Comment by sabineschaller** [comment]
@wilsonianb If you promise to have another look at
- #1181

I can take this.
