### ISSUE TITLE
Backend: Add client id to resource models

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#506]
The client id is an opaque identifier. It is used to filter resources when sending a `list` request.

Example: Coil is the client but the web app and the phone app have different keys. When Coil wants to read all payments it has created, it will call the list endpoint with a token that corresponds to a grant which includes the `list` action. The introspection response from the AS must include the `client_id` that can then be used to filter the payments before returning.

**Comment by wilsonianb** [comment]
`clientId` can be added as a column in the `grants` table.
Add `grantId` as a foreign key in both the `incomingPayments` and `outgoingPayments` tables.
In the [auth middleware](https://github.com/interledger/rafiki/blob/main/packages/backend/src/open_payments/auth/middleware.ts#L36), add the valid grant (with its `clientId`) to the `grants` table (via a new `GrantService`?). (This means [`createOutgoingPayment`](https://github.com/interledger/rafiki/blob/main/packages/backend/src/open_payments/payment/outgoing/service.ts#L99) should stop storing grants, and grant locking can be relocated #485)
The grant is already being added to the `ctx`, so `clientId` will be accessible to subsequent middlewares via `ctx.grant.clientId`

**Comment by wilsonianb** [comment]
This is also needed for quotes to enforce a limit on clients with a grant to `read` (not `read-all`) quotes.
