### ISSUE TITLE
Design Rafiki Admin UI

### ISSUE THREAD

**Issue by matdehaast** [interledger/rafiki#510]
We need to design the admin UI for Rafiki

**Comment by SarahCoilAccount** [comment]
The initial goal is to implement `peer` and `asset` functionality. So when you click the Peers menu you'll see all the peers in a table summary view. You can click on a peer or search for it in the search bar. You can delete a peer directly from the table view. You can click to go to a new page to create a new peer. All this functionality will be mimicked with Assets as well. 

Further functionality for payment pointers and payments (including quotes) can be added as a next step.

Have a look at the Figma designs and leave comments there.
https://www.figma.com/file/0ditBzfQRxx3LW258NJbWZ/Rafiki-Admin-UI?node-id=0%3A1&t=VvycQL23JKaq2Hh7-1
