### ISSUE TITLE
Document the integration between Rafiki, OpenAPI Spec & openpayments.guide

### ISSUE THREAD

**Issue by AlexLakatos** [interledger/rafiki#512]

**Comment by sabineschaller** [comment]
When a PR to change the spec is merged into the open-payments repo, the changes show up on openpayments.guide automatically (done via github actions).
To update the OpenAPI spec validator within Rafiki, update the link to the spec file in `packages/backend/src/config/app.ts`. Make sure to use the url with the commit hash and not `main`. You will then need to go and change the code in `packages/backend/src/open_payments` to reflect the spec changes.

**Comment by sabineschaller** [comment]
Same goes for the auth package.
