### ISSUE TITLE
Create Admin APIs Postman Collection

### ISSUE THREAD

**Issue by AlexLakatos** [interledger/rafiki#516]

**Comment by sabineschaller** [comment]
During the summit the initial implementation of the postman collection and the actual implementation of Rafiki drifted. Specifically how Payment Pointers are created. The postman collection needs to be updated and should work against the latest version of Rafiki that is intended for a v1 release.

**Comment by wilsonianb** [comment]
https://www.postman.com/interledger/workspace/interledger/pull-request/e690baa2-f282-4a43-8d45-8c8b72c528f5?workspace=fd712d53-6058-4110-8449-0e160ea62129

**Comment by sabineschaller** [comment]
Going to check that it's up to date and add newly added endpoints.
