### ISSUE TITLE
Backend changes for Tigerbeetle LSM Backend

### ISSUE THREAD

**Issue by koekiebox** [interledger/rafiki#518]
# Overview

The following chores originated from PR https://github.com/interledger/rafiki/pull/452 as part of the review, although not strictly part of the upgrade to the new version, these changes must also be incorporated to Rafiki:

- [x] #972
- [x] #968
- [x] #967
- [x] #966
- [x] #965
- [x] #964
- [x] #963
- [x] #962
- [x] #961
- [x] #982 
- [x] https://github.com/interledger/rafiki/issues/1009
- [x] Ensure all tasks/comments from https://github.com/interledger/rafiki/pull/452 is addressed

### Snippet 1
```
export interface CommitTransferOptions extends CreateTransferOptionsBase {
  commitId?: string | bigint
  rollbackId?: never
}

export interface RollbackTransferOptions extends CreateTransferOptionsBase {
  commitId?: never
  rollbackId?: string | bigint
}

export type CreateTransferOptions = CommitTransferOptions | RollbackTransferOptions
```

### PR:
https://github.com/interledger/rafiki/pull/452

### Related Issues:
https://github.com/interledger/rafiki/issues/381
https://github.com/interledger/rafiki/issues/521

**Comment by sabineschaller** [comment]
Further todo:
- #982
