### ISSUE TITLE
Add support for CRDB

### ISSUE THREAD

**Issue by matdehaast** [interledger/rafiki#528]
Add support for Rafiki to be able to run against CRDB as a datastore. We previously had issues with knex migrations but that has potentailly be fixed by upgrading our knexjs version. 

https://github.com/knex/knex/issues/2002

**Comment by omertoast** [comment]
You can follow the development from [this branch](https://github.com/interledger/rafiki/tree/omesh-crdb). Unfortunately, Cockroach DB does not support `SKIP LOCKED` on the main branch (support starts at [v22](https://www.cockroachlabs.com/docs/releases/index.html#v22-2) but it's in alpha at the time of the writing). You can keep track of Cockroach releases and when v22 becomes stable, we can use it.
