### ISSUE TITLE
Expand on "New to interledger" section in readme

### ISSUE THREAD

**Issue by cairin** [interledger/rafiki#55]
Should we include links to the Interledger docs or something that introduces people to the different features of Interledger that Rafiki will expose? I like what they did here https://github.com/mozilla/glean.js

**Comment by vladimirfomene** [comment]
@cairin , I think this will help people who are new to the project like me. Knowing what parts of the Interledger protocol suite are implemented will help newbies quickly get a grasp of the codebase.

**Comment by vladimirfomene** [comment]
@cairin is there documentation, where I can get a hold of the Rafiki architecture, understand what services/API it exposes?

**Comment by cairin** [comment]
@vladimirfomene #71 adds the documentation you're looking for.

**Comment by vladimirfomene** [comment]
Thanks @cairin! My weekend will be interesting!
