### ISSUE TITLE
Host auth server api endpoints intended for IDPs on separate server

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#560]
Host the following on a separate server from the main AS:
```
GET /grant/:interactId/:nonce
POST /grant/:interactId/:nonce/accept
POST /grant/:interactId/:nonce/reject
```

**Comment by sabineschaller** [comment]
related to 
- #466

**Comment by njlie** [comment]
Looking back on this I don't think this is necessary anymore. The endpoints listed in the body of this issue ended up becoming endpoints that an AS should extend _for_ an Identity Provider, so they have a reason to belong on the auth server. I think #466 is probably more relevant as it would more clearly separate what's a GNAP implementation and what's an implementation of a process that GNAP describes but doesn't specify.
