### ISSUE TITLE
Document Grant Interaction Flow

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#570]
Once a grant is initialized, there are four main endpoints that are used as part of an interaction to authorize the grant, if the AS deems it necessary. The endpoints, in order of their calling, are as follows:

- `GET /interact/:id/:nonce` (made by the client to the AS, establishes an interaction session, redirects browser session to IDP consent screen)
- `GET /grant/:id/:nonce` (made by the IDP to the AS, secured with `x-idp-secret` header, returns grant info for the consent screen to enumerate )
- `POST /grant/:id/:nonce/(accept OR reject)` (made by the IDP to the AS, secured with `x-idp-secret` header, accepts or rejects the grant based on the user's input on the consent screen. **IDP then redirects to `GET /interact/:id/:nonce/finish`**)
- `GET /interact/:id/:nonce/finish` (ends the interaction established by `GET /interact/:id/:nonce`, redirects browser session to client callback. Contains a query param that either indicates a failure, or on success, a `hash` parameter that the client can use to verify the successful interaction, and the `interact_ref` that identifies the interaction on the AS.)
  - Examples include:
    - `?result=grant_rejected` (if interaction was rejected)
    - `?result=grant_invalid` (if grant is not in a state where it may be accepted or rejected, e.g. already approved)
    - `?hash=p28jsq0Y2KK3WS__a42tavNC64ldGTBroywsWxT4md_jZQ1R\HZT8BOWYHcLmObM7XHPAdJzTZMtKBsaraJ64A
     &interact_ref=4IFWWIKYBC2PQ6U56NL1` (if interaction was accepted)
      - `hash` is a `sha-256` hash of values provided by the client in the body of the [grant initialization request](https://docs.openpayments.guide/reference/post) (`interact.finish.nonce`), values returned in the AS response for that request (`interact.finish`), the `interact_ref` provided alongside the `hash`, and the uri of the grant initialization request (`https://auth-server.com/`).
- `POST /continue/:id` ([this should still be accurate](https://docs.openpayments.guide/reference/post-continue), final back-channel request made by client if interaction was successful, AS responds with an access token)

## On `x-idp-secret`
`x-idp-secret` is the name of a header that is used for `GET /grant/:id/:nonce`, `POST /grant/:id/:nonce/accept`, and `POST /grant/:id/:nonce/reject` requests. Its purpose is to secure communications between the IDP and the AS and its value should be a shared secret known to both entities.

To set this up, set the `IDENTITY_SERVER_SECRET` on the AS environment to a value that is also used to configure the IDP's requests to the AS.

**Comment by sabineschaller** [comment]
@njlie is this 👆 still up to date?

**Comment by njlie** [comment]
> * GET /interact/:id/:nonce/finish

@sabineschaller This looks to still be up to date, having gone through the code for the auth server to date, except for one small thing that I updated in the parent comment. This change was that 

`GET /interact/:id/:nonce/finish` 

might return `grant_rejected` in the query string instead of `interaction_rejected` in the original version of this documentation. There is also `grant_invalid` which I've added as well.

**Comment by sabineschaller** [comment]
@njlie Can you create a nice flow diagram and throw it into a markdown file in the documentation directory? We may have to move it to [rafiki.dev](https://github.com/interledger/rafiki.dev) later but I'm ok with having it here for now until @AlexLakatos explains his vision for rafiki.dev to me (or us).

We also have OpenAPI schemas for the interaction endpoints, right? We should have a nice way of displaying them in the same way as we have them displayed for the Open Payments APIs on openpayments.guide. I think that for sure needs to go to rafiki.dev but again we need to coordinate with @AlexLakatos to understand the plan / structure of that site.
