### ISSUE TITLE
Add httpsig to RS token introspection requests

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#576]
https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-7.3

https://github.com/interledger/rafiki/blob/main/packages/backend/src/open_payments/auth/service.ts#L47

- might require: #556 
- required for: #574
- related to: #387

**Comment by wilsonianb** [comment]
Since we're assuming the RS and AS are operated by the same account provider, we can make token introspection http signature validation optional. The AS won't publicly expose that endpoint.

**Comment by matdehaast** [comment]
Closing for now due to AS-RS being in a trusted zone
