### ISSUE TITLE
Add CreateIncomingPayment on the admin graphql

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#580]
We currently can only get and list incoming payments via the graphql api. We want to add support for also creating incoming payment via the graphql api.

**Comment by wilsonianb** [comment]
Is this to create an incoming payment for any payment pointer or only one at this account provider?
If the former, I'm creating an Open Payments client service for #581 that could also do incoming payment creation.

**Comment by wilsonianb** [comment]
> Is this to create an incoming payment for any payment pointer or only one at this account provider? If the former, I'm creating an Open Payments client service for #581 that could also do incoming payment creation.

See:
- #595
