### ISSUE TITLE
Add resource set registration endpoint

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#601]
* `POST /resource`
* RS should identify itself with a key rather than a string or a `kid`
* Return `instance_id` that may be used to identify an RS instead of a key or by reference during token introspection.

https://datatracker.ietf.org/doc/html/draft-ietf-gnap-resource-servers#section-3.4

**Comment by wilsonianb** [comment]
Would this mean:
- the set of resources supported at the AS is dynamic
or 
- custom subsets of a known set (Open Payments) resource can be enabled?

It seems like we'd have to strip out a lot from current AS for the former. And I'm not sure if/how our custom resource access limits are registered in either case.

**Comment by njlie** [comment]
Closing as a consequent of the reasoning in https://github.com/interledger/rafiki/issues/576.

> Closing for now due to AS-RS being in a trusted zone
