### ISSUE TITLE
Validate backend <> account provider requests

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#626]
Write OpenAPI spec for quote request, prices request, and webhook events, to allow the backend and account provider to validate requests and responses.

See: [integration docs](https://github.com/interledger/rafiki/blob/main/docs/integration.md)

Graphql already handles admin api validation.

**Comment by wilsonianb** [comment]
- related to #571

**Comment by sabineschaller** [comment]
Webhooks spec was added with
- #1210

**Comment by sabineschaller** [comment]
Prices (exchange rates) request responses are already validated:

https://github.com/interledger/rafiki/blob/main/packages/backend/src/rates/service.ts#L115

**Comment by mkurapov** [comment]
- Quote route no longer exists
- We have a webhook OpenAPI spec, but no need to validate the request itself
- We validate rate response in route
