### ISSUE TITLE
Add content-digest verification to httpsig verification.

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#655]
The content-digest signature component contains a sha-256 hash of the request body. The AS httpsig verifier should verifiy this hash by hashing the request body and making sure it matches.

**Comment by wilsonianb** [comment]
https://github.com/interledger/httpbis-digest-headers

**Comment by adrianhopebailie** [comment]
https://github.com/interledger/httpbis-digest-headers was written specifically for this case. Use it to verify the digest but also ensure the digest header is part of the signed components.
