### ISSUE TITLE
Audit usages of `assert` outside of tests 

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#661]
There are a handful of usages of `assert` outside of tests. An example in the mock account provider:
https://github.com/interledger/rafiki/blob/main/packages/mock-account-provider/app/lib/accounts.server.ts#L49-L50

We should convert these to throw applicable `Error`s instead, and reserve `assert` usages for tests only.

**Comment by jpsousa78** [comment]
Hey there! I'm interested in working on this issue.

**Comment by wilsonianb** [comment]
It's yours! :vulcan_salute:
