### ISSUE TITLE
Create Open Payments client library

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#663]
The `backend` has some existing Open Payments client functionality for resolving quote/outgoing payment `receiver`s:
- https://github.com/interledger/rafiki/pull/595

This functionality should exist in its own library that is generally usable for any Open Payments client to perform and validate Open Payments requests and responses.

It can include the following pending functionality:
- https://github.com/interledger/rafiki/issues/606
- https://github.com/interledger/rafiki/issues/583
- #587 

This could potentially also export generated Open Payments types (as well as OpenAPI request/response validators):
- #662

**Comment by mkurapov** [comment]
### Remaining work:

#### Handlers

Incoming payment:
- [ ] create
- [ ] complete
- [ ] list/pagination 
   
Outgoing payment:
- [ ] get
- [ ] create
- [ ] list/pagination 

Quote
- [ ] get
- [ ] create

Grant
- [ ] continue
- [ ] cancel

Token
- [ ] rotation
- [ ] revoking

**Comment by mkurapov** [comment]
Remaining issues:

https://github.com/interledger/rafiki/issues/809
https://github.com/interledger/rafiki/issues/810
https://github.com/interledger/rafiki/issues/811
https://github.com/interledger/rafiki/issues/812
https://github.com/interledger/rafiki/issues/813
https://github.com/interledger/rafiki/issues/814
https://github.com/interledger/rafiki/issues/815
https://github.com/interledger/rafiki/issues/816
https://github.com/interledger/rafiki/issues/817

Currently blocked:
https://github.com/interledger/rafiki/issues/818

**Comment by mkurapov** [comment]
Remaining issues:

- https://github.com/interledger/rafiki/issues/809
- https://github.com/interledger/rafiki/issues/810
- https://github.com/interledger/rafiki/issues/811
- https://github.com/interledger/rafiki/issues/812
- https://github.com/interledger/rafiki/issues/813
- https://github.com/interledger/rafiki/issues/814
- https://github.com/interledger/rafiki/issues/815
- https://github.com/interledger/rafiki/issues/816
- https://github.com/interledger/rafiki/issues/817
- https://github.com/interledger/rafiki/issues/662
- https://github.com/interledger/rafiki/issues/818

**Comment by mkurapov** [comment]
Feature parity complete, closing this issue. Only outstanding related issues to the `open-payments` client are 
- #662 
- #970
