### ISSUE TITLE
Add sig support to postman collection

### ISSUE THREAD

**Issue by matdehaast** [interledger/rafiki#665]
Currently the postman collection does not do request signing. Someone needs to dive deep into postman and work out how we can support the full sig requirements for Open Payments.

This is a tricky problem and please speak to @wilsonianb @sabineschaller @AlexLakatos @matdehaast if you want to begin on this issue.

**Comment by wilsonianb** [comment]
We might be able to sign (using Open Payments library?) in a pre-request script:
- https://blog.postman.com/adding-external-libraries-in-postman/
- https://github.com/interledger/rafiki/issues/663
