### ISSUE TITLE
Create Payment Pointer for Rafiki instance itself

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#668]
Means of identifying the Rafiki instance on OP calls to other Rafiki instances. It
* should not have asset details
* should have parsed/provisioned private key associated with itself

**Comment by wilsonianb** [comment]
Resolved by:
- https://github.com/interledger/rafiki/pull/638
- https://github.com/interledger/rafiki/pull/758

The Rafiki backend now serves its client public jwk from the `/jwks.json` path of its configured:
https://github.com/interledger/rafiki/blob/48cdfa261ce6857810cd1e5a080c411788db5da2/packages/backend/src/config/app.ts#L45-L48
The backend does _not_ currently serve a root payment pointer response.
This can be revisited if we determine the payment pointer will need to be queried (such as if an AS will want client display info for an interactive grant request).
