### ISSUE TITLE
Support pagination for payment pointer keys

### ISSUE THREAD

**Issue by omertoast** [interledger/rafiki#702]
- https://github.com/interledger/rafiki/pull/681#discussion_r1005652929
- https://github.com/interledger/rafiki/pull/681#discussion_r1005694891

**Comment by wilsonianb** [comment]
As is, `/jwks.json` returns all of the payment pointer's keys.
I don't see a way to support pagination for that, so I think we should cap the number of keys for a payment pointer.

Currently, the admin api does not support a payment pointer key lookup, so I think pagination should be added for that.
:point_down: would make adding pagination easier
- https://github.com/interledger/rafiki/issues/701

**Comment by sabineschaller** [comment]
related to
- #701
