### ISSUE TITLE
Add `grantReferenceService.getOrCreate`

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#703]
https://github.com/interledger/rafiki/pull/672#discussion_r1000773412

replace
https://github.com/interledger/rafiki/blob/603df09615a2f458227baf3e23f99b3a0b103921/packages/backend/src/open_payments/auth/middleware.ts#L48-L66

with a method: `grantReferenceService.getOrCreate`

**Comment by mkurapov** [comment]
@raducristianpopa we'd need to add you to the org to be able to assign you to the issue I believe

**Comment by AlexLakatos** [comment]
Sent @raducristianpopa an invite.

**Comment by mkurapov** [comment]
Closed since `grantReferences` are no longer a thing: https://github.com/interledger/rafiki/pull/800
