### ISSUE TITLE
`open-payments` build failing

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#715]
- https://github.com/interledger/rafiki/pull/709 has introduced a build error for `open-payments`

Both `pnpm -r build` and `pnpm --filter open-payments build` produce
```
src/client/requests.ts:36:5 - error TS2322: Type 'ValidatedResponse<T>' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'ValidatedResponse<T>'.
```

However, building `open-payments` isn't currently being tested in the GitHub Actions, because we only run:
https://github.com/interledger/rafiki/blob/d41fa3cab5d3aad267efe8d0459de766d05b0a9e/.github/workflows/lint_test_build.yml#L82
which doesn't include `open-payments` because it is currently excluded in 
https://github.com/interledger/rafiki/blob/d41fa3cab5d3aad267efe8d0459de766d05b0a9e/tsconfig.json#L2-L14

**Comment by wilsonianb** [comment]
I think the build error will be resolved by:
- https://github.com/interledger/rafiki/pull/705

**Comment by mkurapov** [comment]
@wilsonianb I'll merge in master into https://github.com/interledger/rafiki/pull/705 and make sure 🆗

**Comment by wilsonianb** [comment]
@mkurapov want to go ahead and add `open-payments` to [`tsconfig.json`](https://github.com/interledger/rafiki/blob/main/tsconfig.json) in that pr?

**Comment by mkurapov** [comment]
@wilsonianb on it :+1:
