### ISSUE TITLE
Decouple STREAM

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#747]
ILP [STREAM](https://interledger.org/rfcs/0029-stream/) isn't necessary the best fit for Rafiki payments, at least in the near term.

Rafiki only uses configured trusted ILP peers.
Prospective Rafiki operators have indicated they will likely only allow transacting with direct peers, with no intermediary connectors, which Rafiki doesn't even support yet:
- https://github.com/interledger/rafiki/issues/584

An alternative ILP transport is STREAM's predecessor [PSKv2](https://interledger.org/rfcs/0025-pre-shared-key-2/), which should support single packet quoting and sending, but whose library appears [deprecated](https://github.com/interledger-deprecated/ilp-protocol-psk2)?

- related to https://github.com/interledger/open-payments/issues/219

**Comment by sabineschaller** [comment]
@adrianhopebailie mentioned that Mojaloop's transport protocol may be an alternative. @adrianhopebailie can you link that please?

@justmoon would that complicate Dassie <> Rafiki payments? What are your general thoughts on that idea? I know that you always have the analogy that we also use TCP/IP locally.

Basically, I wonder whether we complicate things by allowing different transport layer protocols.

**Comment by adrianhopebailie** [comment]
The Mojaloop APIs are here:
https://docs.mojaloop.io/api/fspiop/
