### ISSUE TITLE
Use public httpsig library in AS for tests

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#751]
Use [publically maintained `httpsig` library](https://github.com/dhensby/node-http-message-signatures) to generate signatures & signature inputs for tests. 

* Content-Digest generation does not seem to be in the scope of this package, so the AS testing helpers should still handle that.
  * https://github.com/interledger/httpbis-digest-headers

**Comment by wilsonianb** [comment]
We could export this from `open-payments` to use in `auth`:
https://github.com/interledger/rafiki/blob/461fb760973f5e241b80404057a53916f72ee8c4/packages/open-payments/src/client/signatures.ts#L26-L30
I'm currently throwing together a branch to test the upcoming version of `http-message-signatures`, which adds signature verification and `ed25519` support:
- https://github.com/dhensby/node-http-message-signatures/pull/27
