### ISSUE TITLE
Demo grant request failing

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#790]
The demo **Grant Request Incoming Payment** Postman request is currently failing with:
```
local-database-1      | 2022-11-28 01:32:28.608 UTC [70] ERROR:  null value in column "clientKeyId" of relation "grants" violates not-null constraint
```

I think this is due to:
https://github.com/interledger/rafiki/blob/5a19201523ec1a9cc2c65fc9930caaafb221de96/infrastructure/local/peer-docker-compose.yml#L17
which bypasses `clientKeyId` being defined in:
- https://github.com/interledger/rafiki/pull/769

This could be solved with:
- https://github.com/interledger/rafiki/issues/737

**Comment by mkurapov** [comment]
@wilsonianb In the meantime, until we have decided on and rolled out #737 , I was thinking we could do something like this:

https://github.com/interledger/rafiki/pull/792/files#r1033413462

i.e. we could provide a key via the header in the meantime

**Comment by mkurapov** [comment]
@raducristianpopa I believe you will need this fix as well to test your open PR, tagging you so you can follow along

**Comment by mkurapov** [comment]
Should be closed once https://github.com/interledger/rafiki/pull/797 is merged

**Comment by mkurapov** [comment]
Closing as #797 makes the demo work
