### ISSUE TITLE
Rotate expired grant access token for incoming payment lookup from one Rafiki to another

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#795]
https://github.com/interledger/rafiki/pull/779#discussion_r1033736498

https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-6.1
>   If the client instance has an access token and that access token
   expires, the client instance might want to rotate the access token.
   Rotating an access token consists of issuing a new access token in
   place of an existing access token, with the same rights and
   properties as the original token, apart from an updated expiration
   time.

**Comment by wilsonianb** [comment]
requires `open-payments` token rotation
- https://github.com/interledger/rafiki/issues/663#issuecomment-1327622353

**Comment by mkurapov** [comment]
Made this into own issue: https://github.com/interledger/rafiki/issues/813
