### ISSUE TITLE
Allow RO to revoke grant / access token

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#803]
Resource owner should be able to revoke a grant via the RS(?) as an alternative to via the client (who would revoke the token via GNAP)

https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-1.5
>_Finalized_  After the access tokens are issued, if the AS does not
      allow any additional updates on the grant request, the grant
      request enters the _finalized_ state.  **This state is also entered
      when an existing grant request is revoked by the client instance
      ([Section 5.4](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-5.4)) or otherwise revoked by the AS (such as through out-
      of-band action by the RO).**

**Comment by wilsonianb** [comment]
Should this happen via an AS admin api?

**Comment by sabineschaller** [comment]
Move introspection to different admin router and add these two 

-     listing grants
-     revoking grants

as REST endpoints to that.

**Comment by sabineschaller** [comment]
Actually, we are having a change of hearts. Listing and revoking grants should be on an auth server Graphql admin API. @domin191013 I hope you haven't gotten too far with this already. And I'll create a new issue for moving the introspection endpoint to a new router.

**Comment by domin191013** [comment]
@sabineschaller  Yup, not yet far away. By the way can you please add some more details? Thanks

**Comment by wilsonianb** [comment]
I imagine this will look a lot like the `backend`'s graphql admin api
https://github.com/interledger/rafiki/tree/main/packages/backend/src/graphql

**Comment by sabineschaller** [comment]
@domin191013 let me know if @wilsonianb 's reference is enough or whether you need more details 🙂.

**Comment by domin191013** [comment]
I think I need to add 2 functions to graphql 
https://github.com/interledger/rafiki/tree/main/packages/backend/src/graphql

listing grants
revoking grants

Is there a way to test after adding these? Or just unit testing would be enough for now?
@sabineschaller

**Comment by wilsonianb** [comment]
You'll end up adding at least
- `packages/auth/codegen.yml`
- `packages/auth/src/graphql/resolvers/grant.ts`
- `packages/auth/src/graphql/resolvers/grant.test.ts` (unit tests)
- `packages/auth/src/graphql/resolvers/index.ts`
- `packages/auth/src/graphql/schema.graphql`

You can look at the corresponding files in `backend` for reference.

**Comment by mkurapov** [comment]
@domin191013 my PR adds a new mutation: https://github.com/interledger/rafiki/pull/986, you can use this as a reference to see how the GraphQL side works. 

I first wrote a new mutation in `packages/auth/src/graphql/schema.graphql` and then ran `pnpm generate` to create TypeScript types that you can use in the resolvers.

**Comment by domin191013** [comment]
@mkurapov  @wilsonianb Can you please check revokeGrant function if I'm in the right way?
Also this currently have issues in testings.
![image](https://user-images.githubusercontent.com/101926344/213904620-a4de11f5-6901-4b09-b045-672f11262d6b.png)
Anyone has idea about why this happens?

**Comment by domin191013** [comment]
https://github.com/interledger/rafiki/pull/1013

**Comment by mkurapov** [comment]
@domin191013 leaving some PR comments right now.

I think if you are running the local environment it's possible you are using that port already
