### ISSUE TITLE
Add a name field for the Peer model in the GraphQL schema

### ISSUE THREAD

**Issue by SarahCoilAccount** [interledger/rafiki#827]
Currently the GraphQL schema model for a Peer is:
```
type Peer implements Model {
  id: ID!
  maxPacketAmount: UInt64
  http: Http!
  asset: Asset!
  staticIlpAddress: String!
  createdAt: String!
}
```
An optional `name` field needs to be added so that there is a field which is easy to use and remember when looking at, or searching for specific peers.

**Comment by mkurapov** [comment]
Tasks: 

- [ ] Add optional `name` to `Peer` model
- [ ] Add optional `name` to `CreatePeerInput`
- [ ] Update mock-account-provider seeding to provide `name` variable during peer creation
