### ISSUE TITLE
Test that starting an interaction includes display information in the redirect URI

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#842]
https://github.com/interledger/rafiki/blob/8054dc567267f7a329198c150b46a623d95a6f8b/packages/auth/src/grant/routes.test.ts#L421-L423

When starting an interaction the AS is supposed to include a `clientName` and `clientUri` in the redirect uri for an IDP to parse and use when presenting a consent screen to a user. The associated test for interaction start route should make sure that these values are included.

**Comment by sabineschaller** [comment]
related to #734
