### ISSUE TITLE
Calculate interaction hash

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#871]
https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-1.6.2
https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-4.2.3

Should the client be calculating the hash in our interactive demo?

Should hash calculation be offered by the `open-payments` package? Could it be part of the continuation request?

**Comment by sabineschaller** [comment]
@njlie can you comment on these questions? You worked a lot on interaction code and docs.

**Comment by njlie** [comment]
From [datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-4.2.3](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-4.2.3)
```
The AS MUST always provide this hash, and the client instance MUST validate the hash when received.
```

> Should the client be calculating the hash in our interactive demo?

Probably not, the client should only validate the hash.

> Should hash calculation be offered by the open-payments package? Could it be part of the continuation request?

Makes sense to me. It's calculated as part of finishing an interaction, though. The client uses an interaction reference that's provided in the redirect induced by finishing an interaction, and after the client has determined the hash also provided in the redirect is valid as well.

**Comment by njlie** [comment]
Following up on this, I think there isn't a need to include hash calculation in the open payments library as it's an implementation detail of GNAP, rather than of open payments. And the client doesn't calculate the hash right now, so no change needs to be made there. Closing as not planned.
