### ISSUE TITLE
Allow IDP to specify reason for rejecting a grant during interaction?

### ISSUE THREAD

**Issue by njlie** [interledger/rafiki#886]
An IDP may have different reasons for rejecting a grant. The most typical reason would be that the resource owner denies the request through the IDP. But it might be necessary to also indicate that the IDP determined that the resource was not owned by the person in question.

**Comment by sabineschaller** [comment]
What does this add? What would the AS do if there were different reasons? Would it communicate that to the client?

**Comment by njlie** [comment]
What it would add is context for why it failed, mostly. It might be useful for a client to know if an interaction failed because the resource owner doesn't actually own the resource the client wants as opposed to the resource owner denying access. The AS shouldn't do anything differently, so this isn't strictly necessary nor is it in the GNAP spec

**Comment by mkurapov** [comment]
Not needing until asked for
