### ISSUE TITLE
GraphQL resolver needs regex check for HTTP endpoints as URLs

### ISSUE THREAD

**Issue by SarahCoilAccount** [interledger/rafiki#958]
When creating a peer using a GraphQL request there is currently no check that the HTTP endpoint supplied is a valid URL. The resolver function should contain a check for this and return an appropriate error if it's invalid.

**Comment by wilsonianb** [comment]
and/or the peer service should be validating the endpoints on peer creation

**Comment by raducristianpopa** [comment]
Should we use the `URL` object over a regex ?

**Comment by mkurapov** [comment]
@raducristianpopa I like the idea of just using the `URL` object :+1:
