### ISSUE TITLE
Rename the commit and rollback operations to suite Tigerbeetle `void/post` naming convention

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#961]

**Comment by wilsonianb** [comment]
https://github.com/interledger/rafiki/blob/dc909a6e73aec9064fd144b0a79fa74aceb07c88/packages/backend/src/accounting/service.ts#L76-L77
https://github.com/interledger/rafiki/blob/dc909a6e73aec9064fd144b0a79fa74aceb07c88/packages/backend/src/accounting/service.ts#L124-L125
https://github.com/interledger/rafiki/blob/dc909a6e73aec9064fd144b0a79fa74aceb07c88/packages/backend/src/accounting/service.ts#L361-L409

**Comment by wilsonianb** [comment]
I don't think we _have_ to reflect tigerbeetle naming throughout rafiki

**Comment by sabineschaller** [comment]
You are right but it's harder for new devs that look at Rafiki and TB together to understand what is going on.

**Comment by raducristianpopa** [comment]
Tigerbeetle is still a bit of a black box for me. To make sure I've understood TB's docs correctly, `commit` should be renamed to `post` and `rollback` to `void`, right ?
