### ISSUE TITLE
Do not fetch the original txn when doing a rollback or commit. 

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#964]
The debit/credit accounts may be set to `0n`, which will allow TB to lookup the original debit/credit accounts.

related to: 
- #968 
- #966

**Comment by wilsonianb** [comment]
https://github.com/interledger/rafiki/issues/965#issuecomment-1380590708

**Comment by wilsonianb** [comment]
- https://github.com/interledger/rafiki/pull/452#discussion_r952354641
