### ISSUE TITLE
Create functions `commitAccountWithdrawal` / `rollbackAccountWithdrawal` with only `withdrawalId` as parameter

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#967]
Related to #968

**Comment by wilsonianb** [comment]
This is already the case
https://github.com/interledger/rafiki/blob/dd07d2ff6f157c8b3fd671e9d74f7ea86e91ee5b/packages/backend/src/accounting/service.ts#L95-L96
https://github.com/interledger/rafiki/blob/dd07d2ff6f157c8b3fd671e9d74f7ea86e91ee5b/packages/backend/src/accounting/service.ts#L456-L459
https://github.com/interledger/rafiki/blob/dd07d2ff6f157c8b3fd671e9d74f7ea86e91ee5b/packages/backend/src/accounting/service.ts#L488-L491
