### ISSUE TITLE
Test unknown stream destination account

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#974]
Test that the connector's account middleware throws `UnreachableError` when `getAccountByDestinationAddress` returns `undefined` when there's a `ctx.state.streamDestination`
https://github.com/interledger/rafiki/blob/421d89ac7883cec8d0f9f5a0d31cda98b6a9a448/packages/backend/src/connector/core/middleware/account.ts#L102

**Comment by Jacintomuambumba** [comment]
Can you assign this issue to me so I can work on it?

@wilsonianb

**Comment by sabineschaller** [comment]
It's yours. Sorry for the late reply.
